### ISSUE TITLE
Subdomains support

### ISSUE THREAD

**Issue by zoran995** [mapfish/mapfish-print#1254]
Is there support for defining subdomain for tiled servers for example `https://{1-4}.base.maps.ls.hereapi.com` (per [link](https://developer.here.com/documentation/map-tile/dev_guide/topics/request-constructing.html)) or `http://{s}.basemaps.cartocdn.com/{basemap-name}/{z}/{x}/{y}@2x.png`
generally, all the maps with a subdomain in format `{s}.tiles.site.com/mylayer/{z}/{x}/{y}.png`, `{s}` should be replaced with a defined list of possible subdomains.

**Comment by sbrunner** [comment]
As I know it's not supported because it's not needed, this is a trick to be able to download faster the tiles in the browser who limit to 3 contents download on a DNS name...

**Comment by zoran995** [comment]
thanks
