### ISSUE TITLE
Snapshot builds outdated

### ISSUE THREAD

**Issue by mlechner** [mapfish/mapfish-print#1393]
**SNAPSHOT builds referenced on mp3 Homepage**
* MapFish print version: since 3.8-SNAPSHOT

**Describe the bug**
Is there a place where I can find recent mapfishprint 3 snapshot builds (print-servlet *.war)?
https://oss.sonatype.org/content/repositories/snapshots/org/mapfish/print/print-servlet/ (refernced on mp3 homepage: http://mapfish.github.io/mapfish-print-doc/download.html) seems to be outdated as the most recent SNAPSHOT is a 3.8 from 2017.

Where to find recent snapshot builds?

**Comment by sbrunner** [comment]
We don't have any more snapshot build, and the latest war are available at GitHub packages: https://github.com/orgs/mapfish/packages 
By the way, the documentation should be updated...
