### ISSUE TITLE
Upgrade from 3.0 to 3.20.3

### ISSUE THREAD

**Issue by samMarseille** [mapfish/mapfish-print#1405]
When upgrading  Mapfish 3.0 to 3.20.3
* MapFish print version: 3.20.3
* Java version: 7
* OS: windows serveur 2012

**Mapfish print won't work when upgrading from  3.0 to 3.20.3**

We  receive an error message since we upgrade the mapFish version. But for us the error message (beside) has no relation with the actual problèm: We only send a "bbox" attribute.

error message
we receive this error message :
Error while processing request:
```
org.locationtech.jts.util.AssertionFailedException: Expected 0 but encountered 284: 
Errors were detected when analysing the @OneOf dependencies of 'mapAttribute': 

	* The OneOf choice: MapBounds was not satisfied.  One (and only one) of the following fields is required in the request data: org.mapfish.print.attribute.map.ZoomToFeatures zoomToFeatures, org.mapfish.print.attribute.map.AreaOfInterest areaOfInterest, double[] bbox, double[] center
```

**How to reproduce**
We simply call the web api with a POST request:
http://TomcatServer/print-servlet-3.20.3/print/somei/buildreport.pdf

The json, config.yaml and the jrxml are in the zip file.
[post.zip](https://github.com/mapfish/mapfish-print/files/4891333/post.zip)

**Actual results**

we receive this error message :
Error while processing request:
```
org.locationtech.jts.util.AssertionFailedException: Expected 0 but encountered 284: 
Errors were detected when analysing the @OneOf dependencies of 'mapAttribute': 

	* The OneOf choice: MapBounds was not satisfied.  One (and only one) of the following fields is required in the request data: org.mapfish.print.attribute.map.ZoomToFeatures zoomToFeatures, org.mapfish.print.attribute.map.AreaOfInterest areaOfInterest, double[] bbox, double[] center
```
Put the logs here.
they're is not error in log

**Expected results**

we expect a .pdf

**Comment by sbrunner** [comment]
Your config asks for a parameter named `map1`, and in your request you provide `map`...

**Comment by samMarseille** [comment]
Thank you for your reply,
I'm still facing issues, now i'have an other error message : 
	* map1 : org.mapfish.print.attribute.map.MapAttribute$MapAttributeValues expected type: java.lang.String
Yet i'm using the examples (config.yaml, report.jrxml ) so i can't figure what kind of attribute is expected.
Thank you again for your reply.
Best regards.

**Comment by samMarseille** [comment]
ok for me
