### ISSUE TITLE
Missing tag for version 2.1.0

### ISSUE THREAD

**Issue by sweco-sebhar** [mapfish/mapfish-print#147]
Released in maven central 19-Jun-2014 but it seems this release was not tagged in Git?

**Comment by sweco-sebhar** [comment]
@jesseeichar still missing tags for versions 2.1.0 and 2.1.1 released in Maven Central.

**Comment by jesseeichar** [comment]
Done.

**Comment by sweco-sebhar** [comment]
Thanks!
