### ISSUE TITLE
Fetch tiles in parallel

### ISSUE THREAD

**Issue by jesseeichar** [mapfish/mapfish-print#157]
Right now tiles for a layer are requested one after the other, not in parallel.

https://github.com/mapfish/mapfish-print/blob/f0a3b27c95dba6e3869c62b1c3fff0d9cac08ded/core/src/main/java/org/mapfish/print/map/tiled/TileLoaderTask.java#L156

**Comment by Jenselme** [comment]
Hi,

Any progress on that issue? I think this would be a real plus in terms of speed.

**Comment by Jenselme** [comment]
Hi,

Any update on that issue?

**Comment by tigerfoot** [comment]
@jesseeichar did you have a rough estimated time for a review of it ?
Trying to convince people about V3 against V2 is hard without ....

What did you need for it?

**Comment by tsauerwein** [comment]
If you are interested in funding the development for this feature, please get in contact with us ([Camptocamp](http://www.camptocamp.com/geospatial/)).
