### ISSUE TITLE
Create single record per page

### ISSUE THREAD

**Issue by 1Map** [mapfish/mapfish-print#1686]
How can you go about doing a single record per page?  Here we have multiple records linked to different stands, but want to print each record (with its map extent) on its own page.

See Example image:

![image](https://user-images.githubusercontent.com/1152458/105013200-aad20300-5a47-11eb-8a52-cb1da377fa9e.png)

**Comment by sbrunner** [comment]
I think you should have a look on this example: https://github.com/mapfish/mapfish-print/tree/master/examples/src/test/resources/examples/oereb, png result: https://github.com/mapfish/mapfish-print/blob/master/examples/src/test/resources/examples/oereb/expected_output/requestData.png

**Comment by 1Map** [comment]
Thanks, but this does not work as I do get the following error:

`org.yaml.snakeyaml.error.YAMLException: Number of aliases for non-scalar nodes exceeds the specified max=50`

**Comment by sbrunner** [comment]
You should set the environment variable `PRINT_YAML_MAX_ALIASES` to e.-g. `200`

**Comment by 1Map** [comment]
I did set the env variable as follow:

`export PRINT_YAML_MAX_ALIASES=200`

Then restarted tomcat, bust still giving same error message.

**Comment by 1Map** [comment]
Never mind.  Working now - Seems to have been a cache issue.
