### ISSUE TITLE
WMTS requestEncoding REST in V3

### ISSUE THREAD

**Issue by williwasser** [mapfish/mapfish-print#170]
I'am not able to print a WMTS - Layer with requestEncoding REST   
         {   "type": "WMTS",
                "baseURL": "http://wmts1.geo.admin.ch/1.0.0/ch.swisstopo.swissimage/default/%7BTime%7D/21781/%7BTileMatrix%7D/%7BTileRow%7D/%7BTileCol%7D.jpeg",
                "opacity": 1,
                "layer": "ch.swisstopo.swissimage",
                "version": "1.0.0",
                "requestEncoding": "REST",
                "dimensions": ["TIME"],
                "dimensionParams": {"TIME":"20140620"},
                "matrixSet": "21781",
                "imageFormat": "jpeg",
                "dpi": 96,     
                "style":"default",
                "matrices": [
                    {...

--------------
In the log File with DEBUG level I get:
19:54:57.498 [ForkJoinPool-1-worker-32] DEBUG o.m.print.map.tiled.TileLoaderTask - 
	GET  -- http://wmts1.geo.admin.ch/http://wmts1.geo.admin.ch/1.0.0/ch.swisstopo.swissimage/default/%257BTime%257D/21781/%257BTileMatrix%257D/%257BTileRow%257D/%257BTileCol%257D.jpeg
19:54:57.498 [ForkJoinPool-1-worker-32] DEBUG o.m.p.h.ConfigFileResolvingHttpRequestFactory - Executing http request: http://wmts1.geo.admin.ch/http://wmts1.geo.admin.ch.....
------------------
The Request URL seems to double and no Tiles are specified

Thank you
Willi

**Comment by tsauerwein** [comment]
This should be fixed with #211. If not, please feel free to re-open the issue.
