### ISSUE TITLE
MAP_RESOLUTION

### ISSUE THREAD

**Issue by FroehDo** [mapfish/mapfish-print#1763]
Mapserver WMS can be queried with an attribute MAP_RESOLUTION=<dpi>, so the WMS styling is scaled accordingly. Can this be used in mapfish3? If not, could you add this as a feature request?

Example for clarification:
Please take a look at the following excerpt of one of our basemaps at mapserver standard resolution of 72dpi
[https://geoportal.freiburg.de/wms/verma_alkis/alkis_kora?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&CACHEID=4354231&LAYERS=stadtkarte_sw&CRS=EPSG:25832&STYLES=&WIDTH=1960&HEIGHT=542&BBOX=412454.9921889679,5318467.013006791,412714.28371561714,5318538.715051404](url)
and with styling scaled for the print resolution of 300dpi:
[https://geoportal.freiburg.de/wms/verma_alkis/alkis_kora?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&CACHEID=4354231&LAYERS=stadtkarte_sw&CRS=EPSG:25832&STYLES=&WIDTH=1960&HEIGHT=542&BBOX=412454.9921889679,5318467.013006791,412714.28371561714,5318538.715051404&MAP_RESOLUTION=300](url).

I found setWmsCustomParam on the docs but I'm unsure how to use it. Is this what I'm looking for? And could you add an example to the docs?

**Comment by sbrunner** [comment]
It's already automatically done by using the serverType :-)
http://mapfish.github.io/mapfish-print-doc/layers.html#Wms%20Layer

**Comment by FroehDo** [comment]
Ah! That does the trick! Thanks!
