### ISSUE TITLE
Error occurred while reading configuration file

### ISSUE THREAD

**Issue by svareg** [mapfish/mapfish-print#1773]
**Context**

- MapFish print version: 3.26
- Java version: ?
- OS: debian stretch

**Describe the bug**

I just migrated from MFP 3.20.1 to MFP 3.26.
When trying to generate a PDF, the file config.yaml cannot be read :
```
INFO  o.m.p.s.ServletMapPrinterFactory - Loading configuration file: file:/usr/local/tomcat/webapps/ROOT/print-apps/oereb/config.yaml
ERROR o.m.p.s.ServletMapPrinterFactory - Error occurred while reading configuration file 'file:/usr/local/tomcat/webapps/ROOT/printapps/oereb/config.yaml'
```

I've activated DEBUG level in logback.xml:

```
<logger name="org.mapfish" level="DEBUG" />
```

But I cannot get any clear Info about the error.
How can I get more informations about the problem in config.yaml ?

Thanks !

**Comment by jwkaltz** [comment]
At first sight, this seems a project specific issue, not a MapFish Print bug... can we look at that via support?

**Comment by svareg** [comment]
Hello Wolgang,

Thanks for your answer.
Yes, it is 100% related to our project, but for the moment I was just trying to have more log infos in order to see the right error instead of just "Error occurred while reading configuration file".

But I can open a support issue if you prefer.

**Comment by svareg** [comment]
I just opened an issue in Jira.
