### ISSUE TITLE
Status don't works

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#196]
Project datas: 
https://github.com/camptocamp/demo_geomapfish/tree/printV3/print/print-apps/demo

Request:
http://localhost:8080/print-demo-sbrunner/print/demo/status/d398a304-3655-496a-8d8d-645147967137@3b48e85b-eca2-4bef-b918-218a50e1ff3b.json?_dc=1424267133998

I get a 404 error code ...

With the content:
```
<html><head><title>Apache Tomcat/6.0.35 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The requested resource () is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/6.0.35</h3></body></html>
```

**Comment by tsauerwein** [comment]
404 means that the report with the given id does not exist. Did you restart or redeploy after creating the report?

**Comment by sbrunner** [comment]
No

**Comment by tsauerwein** [comment]
Did you resolve this issue? Are you sure that you are using the good URL for the status?

For example if the print application is deployed to `http://localhost:8080/print-demo-sbrunner/` you would create a new report with:
`http://localhost:8080/print-demo-sbrunner/print/georisques/report.pdf`

The URL for the status would be for example:
`http://localhost:8080/print-demo-sbrunner/print/status/cfb0c2e6-f550-46f7-9280-97669a275849@bf02b6d8-4566-4c39-8670-93cacd4ff2b5.json`

We should document the API.

**Comment by sbrunner** [comment]
Every things looks correct but I steel have the issue ...

**Comment by jesseeichar** [comment]
I have found this issue now.  It seems we have a bug where you can't put the appId in the status request.  

In this example the appId (or configId) is demo and thus the build report request is something like (after proxy):

http://localhost:8080/print-demo-sbrunner/print/demo/report.pdf

Since the appId is (demo) naturally the status uses the same pattern:

http://localhost:8080/print-demo-sbrunner/print/demo/status

unfortunately it fails but http://localhost:8080/print-demo-sbrunner/print/status works.  I will make a PR that ensures both work as expected.

**Comment by sbrunner** [comment]
OK, thanks @jesseeichar

**Comment by jesseeichar** [comment]
The fix for this is in PR: https://github.com/mapfish/mapfish-print/pull/204

**Comment by tsauerwein** [comment]
With #204 being merged I think we can close this one. @sbrunner please re-open if it still doesn't work for you.
