### ISSUE TITLE
Document API

### ISSUE THREAD

**Issue by tsauerwein** [mapfish/mapfish-print#201]
URLs to create report, get status, request report

**Comment by jesseeichar** [comment]
The generator is making a broken page.  this was available in the older versions.

**Comment by tsauerwein** [comment]
Basic docs were added with #249 but the following is still missing:

* Document "Create and get report"
* Document the `jsonp` option
* Document the `pretty` option for `capabilities`
* Document "get example request" 
* Document the legacy API
