### ISSUE TITLE
Documentation is built from the wrong version?

### ISSUE THREAD

**Issue by ianturton** [mapfish/mapfish-print#209]
http://mapfish.github.io/mapfish-print-doc/#/downloads is built against version 3.2-SNAPSHOT which never got pushed to sonatype (or has been deleted) this means the links are broken as there is a 3.1-SNAPSHOT directory and a 3.3-SNAPSHOT but no 3.2-SNAPSHOT.  See https://oss.sonatype.org/content/repositories/snapshots/org/mapfish/print/print-servlet/

**Comment by jesseeichar** [comment]
Many thanks Ian,  I will update the docs ASAP
