### ISSUE TITLE
The status count is always 0 ...

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#216]

**Comment by sbrunner** [comment]
And the mean time never changed ...

**Comment by tsauerwein** [comment]
The `count` property should be "the number of print jobs done by the server". I don't see why this would be of interest when requesting the current status of a print job. This is an information that I would rather expect in the metrics.

So, I am in favor of removing the properties `status` and `time` (currently the average time to complete a print job on a server) from the status of a print job. @jesseeichar, what do you think?

But it would make sense to have the progress of the running print job and also the time it took to finish the job.

**Comment by sbrunner** [comment]
The count is the position in the queue, thoes informations are important to inform the user when approximatively the print will be done ...

**Comment by tsauerwein** [comment]
https://github.com/mapfish/mapfish-print/blob/development/core/src/main/java/org/mapfish/print/servlet/MapPrinterServlet.java#L127-133
>  * The number of print jobs done by the cluster (or this server if count is not shared through-out cluster).

**Comment by sbrunner** [comment]
It's not like it that it was defined long times aggo..., and it don't have any meaning in the job status, it will have a meaning in a server status ...

**Comment by tsauerwein** [comment]
> It's not like it that it was defined long times aggo..., and it don't have any meaning in the job status, it will have a meaning in a server status ...

I am not sure I understand.

> The count is the position in the queue, thoes informations are important to inform the user when approximatively the print will be done ...

To you want to display something like "Your print job is number xy in the queue"? In my opinion that is too much information. As a user you just want to print your report and you don't want to care about such internal details.

I am proposing to add the following fields:

* `status`: either "waiting", "running" or "finished"
* `progress`: 0 - 100
* `time`: The time from the moment the job was created until it is finished.

**Comment by sbrunner** [comment]
I want to have message like "Your print job will be done (or start) in about 5 minutes", then if the time and the progress are estimated informations that include the queue time it's ok for me.

**Comment by tsauerwein** [comment]
And how do you want to calculate the waiting time on the client-side? Even if you had the average time it takes to create a report and also the number of jobs in the queue, you still don't know how many jobs could be processed in parallel to calculate the waiting time on the client-side.

And if the user has to wait so long that it would be worth to display the waiting time, the print is definitely too slow.

**Comment by sbrunner** [comment]
a good approximation can be:
if the job is running =>
`Your job is running it will be done in less than one minutes` (I suppose that the average time per job is less than one minute.)
else:
`Your job will be done in about n minutes`
where n is:
`average_time / 2 + average_time * (nb_job_queue / nb_parallel_jobs) + average_time`
where:
`nb_job_queue` is the number of jobs in the queue before the current job,
`nb_parallel_jobs` is the number of parallel jobs (nb servers * nb thread)

This solution is more accurate than the accrual and probably required more configuration.

**Comment by tsauerwein** [comment]
If at all such calculations should be done on the serve side, because there you would have the required information.

But I am still not convinced that this is the right direction. Printing should be something that is done instantly. You don't want to wait minutes just to print a report.

**Comment by sbrunner** [comment]
> If at all such calculations should be done on the serve side, because there you would have the required information.

+1

> But I am still not convinced that this is the right direction. Printing should be something that is done instantly. You don't want to wait minutes just to print a report.

This paradigm make our current print solution relay fragile... 

> Or what use-case do you have in mind where you really would have to wait minutes?

When the print server is overload, when we do many print especially report, A0, ...
And the user should be informed that his print job will not be lost.

Accentually in many case where the server is small and do every thing the print takes nearly one minute and if we have two concurrent job it takes so long than we get timeout...

**Comment by jesseeichar** [comment]
There was a bug in the registry increment value method and the print count was only incremented on failure rather than on success and failure.  

Now the time and count values are incremented closer to the correct amount.

**Comment by jesseeichar** [comment]
I have closed this issue but we probably want to revisit the values put in the registry and the API for reading them.
