### ISSUE TITLE
The name is dupplicate in the capabilities attributes

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#219]
e.g.:
`{"name":"title","name":"title","type":"String"},`

**Comment by tsauerwein** [comment]
Can you give me an example configuration where this happens?

The [capabilities document for demo_geomapfish](http://geomapfish.demo-camptocamp.com/1.6/wsgi/printproxy//capabilities.json?version=d5b26bf97bc94482973c8266b5cba9cb) looks ok:

    {
        "app": "demo",
        "layouts": [
            {
                "attributes": [
                    {
                        "type": "String",
                        "name": "title"
                    },

**Comment by sbrunner** [comment]
Strange I see it here ..., then I close it ...
