### ISSUE TITLE
OSM layer has wrong extent with projection EPSG:25832

### ISSUE THREAD

**Issue by guidoheckmann** [mapfish/mapfish-print#2301]
I would like to include OSM as baselayer for the printed map. I have added it to the layers config:
`      
            "layers": [{
                    "baseURL": "https://tile.openstreetmap.org",
                    "type": "OSM",
                    "imageExtension": "png",
                    "failOnError": true
                }]`

For the map config the setting for projection is
`
        "map": {
            "projection": "EPSG:25832",`

The output should be somewhere in Germany but is in France. I think it has to do with the projection, but there is no setting for type OSM. Is there a solution for this?

**Comment by sbrunner** [comment]
As I know, Mapfish Print can't project an image, then you can't print the OSM tiles in projection EPSG:25832...

**Comment by guidoheckmann** [comment]
Ok, thank you for the info
