### ISSUE TITLE
Add background layers to map

### ISSUE THREAD

**Issue by jesseeichar** [mapfish/mapfish-print#231]
Consider the case where we want all maps to have the same background layers.  To do this currently either the client must post the background layers for each print request, or we must define two maps in the template that are the same size, have most of the same parameters except that the background map will have default layers specified in the background map attribute definition.  Further, the client must be aware of the background map and post the same bbox for both maps.

I suggest adding background layers to the map attribute.  This way the client doesn't need to know about the background layers, they will be added automatically.

I considered putting the background layers in the processor and that might be useful if we don't want the client to override the background layers.  I think for consistency and for flexibility we put the background layers on the MapAttribute

**Comment by sbrunner** [comment]
Can it be a place where we can configure the `!configureHttpRequests` for all the template ?

**Comment by jesseeichar** [comment]
I don't think that would really be the same.  Consider if we want a Postgis layer as a background layer in the map.  It is not a case of modifying a WMS's layer list

**Comment by jesseeichar** [comment]
I have decided that since the MapAttribute is already quite complex it might be wiser to make a processor which represents the background layers and adds them to the MapAttribute.  This way the system is more module and (hopefully) will be simpler to maintain.

**Comment by tsauerwein** [comment]
Done in https://github.com/mapfish/mapfish-print/issues/233
