### ISSUE TITLE
Artifact publishing to central repository

### ISSUE THREAD

**Issue by MrMufflon** [mapfish/mapfish-print#2390]
Hi,
I'm having trouble finding the latest version from 3.22.0 onwards in maven central. Do you plan on publishing there again?
Github packages only provides versions until 3.26.0 currently.

**Comment by jwkaltz** [comment]
Hi @MrMufflon , there are releases here https://github.com/mapfish/mapfish-print/tags , does this contain what you are looking for?

**Comment by MrMufflon** [comment]
Hi @jwkaltz, I was hoping for some kind of artifact repository, that can be integrated in my build infrastructure. Just like where you started using github packages https://github.com/orgs/mapfish/packages?repo_name=mapfish-print

**Comment by sbrunner** [comment]
I just to finish it, now the versions 3.27.x, 3.28.x, 3.29.x are published to GitHub Package repository :-)
