### ISSUE TITLE
Define JSON response for status request

### ISSUE THREAD

**Issue by jesseeichar** [mapfish/mapfish-print#243]
We have been adhoc adding to the status json response without clearly defining what the json should mean.  This issue is for having the discussion about the status response.

So far we have:

    done: true/false
    error: string containing error message.  Optional field
    count: The number of print completed print jobs (includes failed prints)
    time: The amount of average amount time a job takes

Possible additions:

    timeElapsed: The amount of time elapsed since the request was made
    queuePosition: The number of items in the queue ahead of this job
    status: running/waiting/done

**Comment by sbrunner** [comment]
+1, I think that can deprecate the `count`, `time` and `<job request>.position` for me the new set contains relay better values.

**Comment by tsauerwein** [comment]
I am ok with that. Just that I would like to remove the current `count` property because the total number of print jobs is something that makes sense in the metrics but not when requesting the status for a print job.

> I think that can deprecate the `count`, `time` ...

You also want to get rid of `time`? The in the UI you'll only be able to show a message like "There are x jobs ahead of yours" and not "Your job will start in ~4:14min". Is that what you want?

**Comment by sbrunner** [comment]
For the message "Your job will start in about 4 minutes" the time isn't helpful, we needs something like `timeStart: The estimated tine when the job will start`, it should be added :-), who is different then `queuePosition * time` when we have more than one job in parallel.

**Comment by sbrunner** [comment]
The `done` can also be remove it will be replaced by `status`.

**Comment by jesseeichar** [comment]
I don't really want to remove things from the API.  We messed up by adding things we weren't sure we needed, but now that we have had a release we can't really remove them, People might be depending on them.

**Comment by tsauerwein** [comment]
> I don't really want to remove things from the API. We messed up by adding things we weren't sure we needed, but now that we have had a release we can't really remove them, People might be depending on them.

I think it's no problem to deprecate things from the API if we properly document the change and provide alternatives. That's the way we do it with OpenLayers.

**Comment by sbrunner** [comment]
+1 to deprecate, event if we newer remove it, it makes the API clearer :-)
