### ISSUE TITLE
Define JSON response for create print job request

### ISSUE THREAD

**Issue by jesseeichar** [mapfish/mapfish-print#244]
We have been adhoc adding to the createReport json response without clearly defining what the json should mean. This issue is for having the discussion about the createReport response.

Currently we have: 

    ref: The job reference id
    statusURL: The url for obtaining the status of the job

Stéphane suggested `position` to indicate how many jobs are currently being processed.  I am fine with that.  Are there any other values to add to this request?  Maybe estimated time to completion?

**Comment by tsauerwein** [comment]
> Stéphane suggested position to indicate how many jobs are currently being processed. I am fine with that. 

Just to make sure: This `position` would be the queue position ("The number of items in the queue ahead of this job" as you are saying in #243)? And not "the total number of requests made" (as #239 proposes).

I would be ok with the queue position.

**Comment by jesseeichar** [comment]
That was my concept but I am not sure position is possible in status
