### ISSUE TITLE
The average time per job in the status is wrong

### ISSUE THREAD

**Issue by tsauerwein** [mapfish/mapfish-print#246]
It decreases with every request and seems to be wrong (the print takes on average ~10 seconds but the shown time is 2,5 seconds).

Hopefully we will get rid of the average time in the status with #243, but we should make sure that the average time is calculated correctly for the metrics.

**Comment by sbrunner** [comment]
I'm not sure that wrong but the first job take many more time than the others we should probably remove it from the stats ?
