### ISSUE TITLE
Arrangement of the features on the map (mapfish V3)

### ISSUE THREAD

**Issue by hoytGMX** [mapfish/mapfish-print#250]
Dear all,

currently I have the following problem: I want to print a line and some points. In the PDF file the line is above the points.
![example](https://cloud.githubusercontent.com/assets/4170661/8078057/1ba5023c-0f5b-11e5-891d-4c2e76a9f1b6.JPG)

Is there a way to influence the arrangement of the elements?

Kind regards

**Comment by tsauerwein** [comment]
Hi,

you have several options to influence the render order. Either you put your
points and lines into different layers (the layers will rendered in the
order you define in the request). Or you have just one vector layer and
either change the order of the features in the GeoJSON or the order of your
symbolizers in the style definition.

Tobias

**Comment by hoytGMX** [comment]
Thank you for your quick response.
It works like a charme! (:
