### ISSUE TITLE
requestSizeFilter hardcoded

### ISSUE THREAD

**Issue by Styp** [mapfish/mapfish-print#257]
It seems, that the following line is a little hardcoded.
private static final int MAX_CONTENT_LENGTH = 1048576;

Why can not the user decide how big his transfers are?
TomCat has already a few mechanisms to protect from DDOS attacks through huge filesizes. In my humble opinion it would be better to let tomcat handle the size restriction.

**Comment by tsauerwein** [comment]
It definitely makes sense to make this configurable.

**Comment by jesseeichar** [comment]
This is also often a configuration option in the web server.

Jesse

**Comment by Styp** [comment]
This issue can be closed - I had a long journey finding the solution....

The hardcoded configuration is overwritten by the web.xml file.
Adjusting these lines here helped:

    <filter>
        <filter-name>requestSizeFilter</filter-name>
        <filter-class>org.mapfish.print.servlet.RequestSizeFilter</filter-class>
        <init-param>
                
            <param-name>maxContentLength</param-name>
            <param-value>16777216</param-value>
        </init-param>
    </filter>

Maybe it would be better if the adjustment happens in the print-apps config? Just an idea... ;)
