### ISSUE TITLE
Choose file name

### ISSUE THREAD

**Issue by Jenselme** [mapfish/mapfish-print#259]
Currently, when we are printing with mapfish v3, the file name is alway `mapfish-print-report.pdf`. Is there a way to change how the file is named?

**Comment by jesseeichar** [comment]
BTW there is a google group for questions. (https://groups.google.com/forum/#!forum/mapfish-print-users)

But to answer your question:  Yes you can declare the filename.  There are two methods.  One in the configuration and one on the client side.

put in `config.yaml`:

    outputFilename: my-printname

or if you want the date:

    outputFilename: print-${dd-MM-yyyy}

The other option is to sent the desired output name with the print request.  You can add `outputFilename` to the JSON request data.

**Comment by Jenselme** [comment]
Thanks!
