### ISSUE TITLE
Exception when attempting to print an empty GeoJSON layer

### ISSUE THREAD

**Issue by elemoine** [mapfish/mapfish-print#279]
I get an exception when attempting to print a GeoJSON layer with no features and no style rules. This is an exception:

```
Caused by: java.lang.IllegalArgumentException: No rules found in style.  Rules are json objects that have the key * or have the form: [ecql]
```

In my ngeo code I only add style rules when the vector layer includes features. And I would not expect MapFish Print to raise an exception when there are no rules and no features.

**Comment by tsauerwein** [comment]
Which version are using? #247 and #248 addressed similar issues.

**Comment by tsauerwein** [comment]
The following print request works on master:

    {
        "attributes": {"map": {
            "center": [
                -8233518.5005945,
                4980320.4059228
            ],
            "dpi": 128,
            "layers": [{
                "geoJson": {
                   "type": "FeatureCollection",
                   "features": []
                },
                "type": "geojson"
            }],
            "projection": "EPSG:900913",
            "rotation": 0,
            "scale": 100000
        }},
        "layout": "A4 landscape"
    }

Is that what you were using?

**Comment by tsauerwein** [comment]
It's a request like the following:

    {
        "attributes": {"map": {
            "center": [
                -8233518.5005945,
                4980320.4059228
            ],
            "dpi": 128,
            "layers": [{
                "geoJson": {
                   "type": "FeatureCollection",
                   "features": []
                },
                "type": "geojson",
                "style": {"version": 2}
            }],
            "projection": "EPSG:900913",
            "rotation": 0,
            "scale": 100000
        }},
        "layout": "A4 landscape"
    }

**Comment by elemoine** [comment]
Yes.

I finally work around the bug by having the client code just skip empty vector layers entirely. See https://github.com/elemoine/ngeo/commit/67a83029b78164a2f2dfcbe2348b04847447223f.

I am going to close this PR for now. We can revisit this in the future if it's a problem for other MapFish Print clients.
