### ISSUE TITLE
 Why not upload the maven repository

### ISSUE THREAD

**Issue by ChenyuWang98** [mapfish/mapfish-print#2851]
**I see that the current latest print-lib version is 3.30.3, but the latest version in the maven repository is 3.22.0. I want to know why the official stopped uploading maven artfact. Does it mean that 3.22.0 is the last official release version.**

- MapFish print version: 3.30.3
- Java version: 8
- OS: win

**Describe the bug**

I see that the current latest print-lib version is 3.30.3, but the latest version in the maven repository is 3.22.0. I want to know why the official stopped uploading maven artfact. Does it mean that 3.22.0 is the last official release version.

**Comment by ChenyuWang98** [comment]
I see that the latest version is posted to the github maven repository. Curious why such a choice was made, which makes new versions of print-lib undetectable in the maven central repository.

**Comment by sbrunner** [comment]
Because est provided system, it's relay too complicated. :-(

**Comment by ChenyuWang98** [comment]
> Because est provided system, it's relay too complicated. :-(

So 3.30.3 is the last official release. Not uploading maven is because it is too complicated, not because I don't want to upload it.
What should I do if I integrate print-lib via maven?

**Comment by sbrunner** [comment]
You should try to use https://jitpack.io/#mapfish/mapfish-print feedback is welcome to officialize it :-)
