### ISSUE TITLE
Too much information is written to the log file (catalina.out)

### ISSUE THREAD

**Issue by hoytGMX** [mapfish/mapfish-print#292]
When running Tomcat the console output is usually redirected to the file catalina.out. Every time you print the entire JSON is written to the file. If there are several queries the file is filled with irrelevant information.

```
15:23:21.975 [http-bio-127.0.0.1-8080-exec-8710] INFO  p.mapfish.print.servlet.spec - spec:
{"outputFormat":"pdf","layout":"A4 landscape","attributes":{"scalebar":{"align":"right"},"map":{"center":[814999.99999999,6784416.4466588],"scale":1126691.5807062818,"layers":[{"style":{"3":{"fontColor":"#868A08","graphicWidth":28,"externalGraphic"... etc.
```
How can this behavior be stopped?

Kind regards

**Comment by hoytGMX** [comment]
In various files (like shell-info-log.xml), I have found the following comments:
```
<!-- Set spec logger to INFO to log all print spec json data -->
```
Currently all information is written to the logfile. How can I change this?
Does anyone have any suggestions?

A similar problem already existed: [GitHub - Remove all logging for clientConfig from command line](https://github.com/mapfish/mapfish-print/issues/169)

**Comment by tsauerwein** [comment]
The configuration of the spec logger was wrong. When PR #305 is merged, the logging of the specs is turned off by default.

To enable it, you can set the following in `WEB-INF/classes/logback.xml`:

     
     <logger name="org.mapfish.print.servlet.spec" level="INFO" />
