### ISSUE TITLE
`./gradlew jettyRunForeground` don't work

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#295]
Reopened because of broken link, see: https://github.com/mapfish/mapfish-print/issues/295#issuecomment-136284138 and next

---

specified in https://github.com/mapfish/mapfish-print/tree/development/examples
=> 
```
Picked up _JAVA_OPTIONS:  -Dorg.eclipse.swt.browser.XULRunnerPath=~/xulrunner -XX:MaxPermSize=256m  -Dorg.eclipse.swt.browser.XULRunnerPath=~/xulrunner -XX:MaxPermSize=256m 
Defining custom ‘build’ task is deprecated when using standard lifecycle plugin has been deprecated and is scheduled to be removed in Gradle 3.0

FAILURE: Build failed with an exception.

* What went wrong:
Task 'jettyRunForeground' not found in root project 'mapfish-print3'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.465 secs
```

**Comment by tsauerwein** [comment]
This readme was a copy from version 2, I updated it in #303.

**Comment by sbrunner** [comment]
Looks good but the link to the `Readme.rst` and the `config.yaml` are broken ...

**Comment by tsauerwein** [comment]
> Looks good but the link to the Readme.rst and the config.yaml are broken ...

What links?

**Comment by sbrunner** [comment]
The links available at http://localhost:9876/e2egeoserver/ for the readme and sub pages for the config files ...

**Comment by tsauerwein** [comment]
Oh yeah, I cleaned this a bit up, see #307.
