### ISSUE TITLE
Temporary files for JaperReports Fonts

### ISSUE THREAD

**Issue by tsauerwein** [mapfish/mapfish-print#317]
`/srv/tomcat/tomcat1/temp` contains a growing number of temporary files:

```
+~JF389360344564290064.tmp   +~JF6502749721350353714.tmp  +~JF970488590243158887.tmp
+~JF3894623569475325232.tmp  +~JF6507705951610923679.tmp  +~JF977616380673379715.tmp
+~JF3894744403590903750.tmp  +~JF6513326603241611982.tmp  +~JF980815021821411279.tmp
+~JF3895677808956867838.tmp  +~JF6520133340740711101.tmp  +~JF983300708819795455.tmp
+~JF3896200424674733098.tmp  +~JF6522982726906774811.tmp  +~JF987055633544584398.tmp
+~JF3918387078985949926.tmp  +~JF6546625248794724222.tmp  +~JF996878696027450281.tmp
...
```

These files seem to be related to the JasperReports Fonts extension. We have to check why all these files are created and why they are not removed.

See also:
http://community.jaspersoft.com/jasperreports-library/issues/4743
http://stackoverflow.com/questions/23996932/jasperreports-font-extension-jf-tmp-files

**Comment by sbrunner** [comment]
Looks good for me

**Comment by tsauerwein** [comment]
Thanks.

**Comment by tsauerwein** [comment]
Leaving this ticket open, because it's still unclear why the files are not deleted automatically.

**Comment by tsauerwein** [comment]
The `+~JF*.tmp` files are created when JasperReports loads an additional font (for example from jasperreports-fonts). They are removed when the JRE does a proper shutdown (in case the Java process is killed they might not be deleted). There should be only one file for each font, but in case of class loading issues a font might be loaded several times (see also [here](http://community.jaspersoft.com/wiki/answers-most-common-questions-regarding-jfxxxxxtmp-temporary-files)). I think that is the problem that we are seeing.

I wasn't able to reproduce the issue. So, for now we'll delete the files with a clean-up task (#324).
