### ISSUE TITLE
Scale in spec in paging mode

### ISSUE THREAD

**Issue by sureshenercomp** [mapfish/mapfish-print#3227]
Having issue while passing scale for paging in paging config, i attached my request json. i am passing 500 it takes 490 same for other scales  

Please check attached request,json file 
[request.json](https://github.com/mapfish/mapfish-print/files/14611568/request.json)

**Comment by sbrunner** [comment]
Your spec looks good, you see that 490 is got in the scale bar?, on a text you print on the page (using with method?)?
What's your config file?

**Comment by sureshenercomp** [comment]
for every scale it takes little bit less ,like for 1000 it takes 940 ,for 2000 it take 1900,for 4000 it takes 3700.
i am using config from paging example with mapfish.war in tomcat

**Comment by sureshenercomp** [comment]
i am attaching output files 
[AFour500.pdf](https://github.com/mapfish/mapfish-print/files/14613419/AFour500.pdf)
[AFour1000.pdf](https://github.com/mapfish/mapfish-print/files/14613421/AFour1000.pdf)
[AFour2000.pdf](https://github.com/mapfish/mapfish-print/files/14613422/AFour2000.pdf)
[AFour4000.pdf](https://github.com/mapfish/mapfish-print/files/14613423/AFour4000.pdf)

my Config:


templates:
  #===========================================================================
  A4 landscape: !template
  #===========================================================================
    reportTemplate: simpleReport.jrxml
    attributes:
      map: !map
        maxDpi: 400
        width: 780
        height: 330
        default:
            useAdjustBounds: true
      paging: !paging
        default:
          scale: 800
          # overlap: 50
      scalebar: !scalebar
        width: 240
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMapPages {}
    - !createMap {}
    - !createScalebar
      outputMapper: {}
    - !createDataSource
      inputMapper: {}
      attributes:
        scalebar: !scalebar
          width: 240
          height: 40
      processors:
        - !createMap {}
        - !createScalebar {}
    tableData: jrDataSource

**Comment by sbrunner** [comment]
And just notice that you shouldn't print in EPSG:4326, you should use a projection in meter...
Your config is unreadable, please use the code block...

**Comment by sureshenercomp** [comment]
```
templates:
#===========================================================================
A4 landscape: !template
#===========================================================================
reportTemplate: simpleReport.jrxml
attributes:
map: !map
maxDpi: 400
width: 780
height: 330
default:
useAdjustBounds: true
paging: !paging
default:
scale: 800
# overlap: 50
scalebar: !scalebar
width: 240
height: 40
processors:
- !reportBuilder # compile all reports in current directory
directory: '.'
- !createMapPages {}
- !createMap {}
- !createScalebar
outputMapper: {}
- !createDataSource
inputMapper: {}
attributes:
scalebar: !scalebar
width: 240
height: 40
processors:
- !createMap {}
- !createScalebar {}
tableData: jrDataSource


```

**Comment by sureshenercomp** [comment]
what if i not give any projection will it work
