### ISSUE TITLE
Host header should be calculated not forwarded

### ISSUE THREAD

**Issue by arnaud-morvan** [mapfish/mapfish-print#330]
When I set Host in print config !forwardHeaders, it works for internal WMS, but do not for MapQuest tiles http://otile1.mqcdn.com/tiles.

When I remove host from print config !forwardHeaders, it works for MapQuest tiles, but not for internal WMS.

see http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23
If I correctly understand, the host header MUST correspond to the host part of the url, very important for relatives urls (without host in url), for example apache can use it to get the correct vhost for the request.

* http://otile1.mqcdn.com/tiles/1.0.0/osm/17/68213/45687.png

=> the host should be "otile1.mqcdn.com"

* http://aprona-websig.demo.sig.cloud.camptocamp.net/amorvan/wsgi/mapserv_proxy?TRANSPARENT=true&BBOX=817598.10863306%2C6066121.691297%2C819555.10863306%2C6068502.691297&CACHE_VERSION=77c810dfd81542fabbd35429e59b3974&VERSION=1.1.1&FORMAT=image%2Fpng&SERVICE=WMS&HEIGHT=2381&REQUEST=GetMap&LAYERS=stations_hydro&STYLES=&SRS=EPSG%3A3857&WIDTH=1957

=> here the host should be aprona-websig.demo.sig.cloud.camptocamp.net

when I make a wget request, I don't have to precise the host header, it is calculated.

This is a blocking issue, impossible to print with internal WMS over MapQuest tiles.

**Comment by tsauerwein** [comment]
See also https://github.com/mapfish/mapfish-print/pull/321

**Comment by arnaud-morvan** [comment]
Duplicate #321
