### ISSUE TITLE
MFP cannot handle response type 204 no content

### ISSUE THREAD

**Issue by Jenselme** [mapfish/mapfish-print#331]
Hi,

I recently tried to print layers from a WMTS server from Swisstopo using MFPv3. When I did, I got a pink image.

From what I understand, these WMTS layers have many holes in them, so for most tiles, the WMTS server will just answer 204 no content. MFP treats this as an error and print its "error pink image".

However, I expect it to just ignore this tile (or use a full transparent one instead which is equivalent). Can you please correct the behavior of MFP in this case?

# Example

if you go [here](https://beta.geojb.ch/?topic=01_cadastre&lang=fr&bgLayer=voidLayer&layers=WMTS||SWISSIMAGE||Time:20151231||https:%2F%2Fwmts.geo.admin.ch%2F1.0.0%2Fch.swisstopo.swissimage-product%2Fdefault%2F{Time}%2F21781%2F{TileMatrix}%2F{TileRow}%2F{TileCol}.jpeg,CADASTRE,WMTS||R%C3%A9seau%20routier%20VECTOR25||Time:20090401||https:%2F%2Fwmts.geo.admin.ch%2F1.0.0%2Fch.swisstopo.vec25-strassennetz%2Fdefault%2F{Time}%2F21781%2F{TileMatrix}%2F{TileRow}%2F{TileCol}.png,WMTS||R%C3%A9seau%20hydrographique%20VECTOR25||Time:20090401||https:%2F%2Fwmts.geo.admin.ch%2F1.0.0%2Fch.swisstopo.vec25-gewaessernetz%2Fdefault%2F{Time}%2F21781%2F{TileMatrix}%2F{TileRow}%2F{TileCol}.png,WMTS||Objets%20marquants%20VECTOR200||Time:20150101||https:%2F%2Fwmts.geo.admin.ch%2F1.0.0%2Fch.swisstopo.vec200-miscellaneous%2Fdefault%2F{Time}%2F21781%2F{TileMatrix}%2F{TileRow}%2F{TileCol}.png&catalogNodes=&X=230362.74&Y=574757.50&zoom=8) and print, you get:

## errors in the log file:
```
14:59:24.649 [ForkJoinPool-1-worker-50] ERROR o.m.print.map.tiled.TileLoaderTask - Error making tile request: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.vec25-gewaessernetz/default/20090401/21781/26/934/1208.png
        Status: 204
        outMessage: No Content
14:59:24.693 [ForkJoinPool-1-worker-50] ERROR o.m.print.map.tiled.TileLoaderTask - Error making tile request: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.vec25-gewaessernetz/default/20090401/21781/26/934/1209.png
        Status: 204
        outMessage: No Content
14:59:25.544 [ForkJoinPool-1-worker-50] ERROR o.m.print.map.tiled.TileLoaderTask - Error making tile request: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.vec200-miscellaneous/default/20150101/21781/26/935/1208.png
        Status: 204
        outMessage: No Content
14:59:25.588 [ForkJoinPool-1-worker-50] ERROR o.m.print.map.tiled.TileLoaderTask - Error making tile request: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.vec200-miscellaneous/default/20150101/21781/26/935/1209.png
        Status: 204
        outMessage: No Content
14:59:25.630 [ForkJoinPool-1-worker-50] ERROR o.m.print.map.tiled.TileLoaderTask - Error making tile request: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.vec200-miscellaneous/default/20150101/21781/26/934/1208.png
        Status: 204
        outMessage: No Content
14:59:25.672 [ForkJoinPool-1-worker-50] ERROR o.m.print.map.tiled.TileLoaderTask - Error making tile request: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.vec200-miscellaneous/default/20150101/21781/26/934/1209.png
        Status: 204
        outMessage: No Content
```

## pdf capture

![no-content](https://cloud.githubusercontent.com/assets/6643536/10637360/7d9abe9c-7805-11e5-9606-4c062425655a.png)

**Comment by tsauerwein** [comment]
Thanks for reporting this problem! Would you like to work on a PR for it? The relevant code is here:
https://github.com/mapfish/mapfish-print/blob/development/core/src/main/java/org/mapfish/print/map/tiled/TileLoaderTask.java#L289-L319
