### ISSUE TITLE
[GridLayer] Labels in degree are truncated

### ISSUE THREAD

**Issue by mwerlen** [mapfish/mapfish-print#332]
Labels in degree are formatted with "%1.2f" and so truncated too much :
![gridlayer_degree](https://cloud.githubusercontent.com/assets/1324846/10666913/b52e13f2-78d4-11e5-9e91-bf27c4c85900.png)

Faulty code is located at org.mapfish.print.map.geotools.grid.GridUtils#createLabel

My suggestion is to keep existing format for meter based projection and use a "%1.10f" for degree projections

**Comment by tsauerwein** [comment]
> My suggestion is to keep existing format for meter based projection and use a "%1.10f" for degree projections

There could be a `labelFormat` attribute for the grid layer, to make it more flexible.

**Comment by tsauerwein** [comment]
@mwerlen Would #335 work for you?

**Comment by mwerlen** [comment]
#335 is great !
