### ISSUE TITLE
OSM layer always shows as a pink image.

### ISSUE THREAD

**Issue by winsento** [mapfish/mapfish-print#338]
OSM layer always shows as a image with a colour  #ff9b9b. I tried to change the link to `http://tile.openstreetmap.org/` but the same result. 
Test here: http://webmapcenter.de/print-servlet-3.1.2/ with parameters:

```
{"layout":"A4 portrait","attributes":{"map":{"bbox":[1465634.1551512843,5277607.55344709,10881697.645922948,9261326.722619716],"dpi":99,"layers":[{"baseURL":"http://tile.openstreetmap.org/{z}/{x}/{y}.png","opacity":1,"resolutions":[156543.03392804097,78271.51696402048,39135.75848201024,19567.87924100512,9783.93962050256,4891.96981025128,2445.98490512564,1222.99245256282,611.49622628141,305.748113140705,152.8740565703525,76.43702828517625,38.21851414258813,19.109257071294063,9.554628535647032,4.777314267823516,2.388657133911758,1.194328566955879,0.5971642834779395,0.29858214173896974,0.14929107086948487,0.07464553543474244,0.03732276771737122,0.01866138385868561,0.009330691929342804,0.004665345964671402,0.002332672982335701,0.0011663364911678506,0.0005831682455839253,0.00029158412279196264,0.00014579206139598132,0.00007289603069799066,0.00003644801534899533,0.000018224007674497665,0.000009112003837248832,0.000004556001918624416,0.000002278000959312208,0.000001139000479656104,5.69500239828052e-7,2.84750119914026e-7,1.42375059957013e-7,7.11875299785065e-8,3.559376498925325e-8],"tileSize":[256,256],"type":"OSM"}],"projection":"EPSG:3857","rotation":0}}}
```

**Comment by tsauerwein** [comment]
In the logs you can find something like:

    09:48:42.912 [ForkJoinPool-1-worker-8] ERROR o.m.print.map.tiled.TileLoaderTask - Error making tile request: http://tile.openstreetmap.org/04/12/5.png
      Status: 403
      outMessage: Forbidden

It seems that the openstreetmap.org tile servers check for the user-agent (the user-agent sent by MFP is for example "Apache-HttpClient/4.3.3 (java 1.5)"). You *could* change the user-agent for the requests, but it is also a matter of respecting the usage restrictions of the tile servers.

**Comment by MaxComse** [comment]
Just add 
 - !configureHttpRequests
      httpProcessors:
         - !forwardHeaders
           headers: [Referer, User-Agent]
in processor section of config.yaml
