### ISSUE TITLE
v3 doesnt support "Transparent" as color type

### ISSUE THREAD

**Issue by ochriste** [mapfish/mapfish-print#339]
if, in the json sent to MapFishPrint, we have a layer with a style where "Transparent" is set as color,
for example:
```javascript
Object { fillColor="Transparent",  strokeColor="Transparent",  fillOpacity=0.4,  more...}
```
an error occurs in org.mapfish.print.map.style.json.ColorParser.toColor(ColorParser.java:124):
java.lang.NumberFormatException: For input string: "Transparent"

**Comment by tsauerwein** [comment]
I didn't even know that `transparent` is a valid named color, but [apparently](http://www.w3.org/TR/css3-color/#transparent) it is. We can add support for that.

**Comment by sbrunner** [comment]
Project specific ...

**Comment by sbrunner** [comment]
Don't use Transparent in the Style ...
