### ISSUE TITLE
build/logs/logFile.log (No such file or directory)

### ISSUE THREAD

**Issue by ochriste** [mapfish/mapfish-print#367]
11:30:29,909 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[File] - Failed to create parent directories for [/srv/tomcat/tomcat1/build/logs/logFile.log]
11:30:29,909 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[File] - openFile(build/logs/logFile.log,true) call failed. java.io.FileNotFoundException: build/logs/logFile.log (No such file or directory)
        at java.io.FileNotFoundException: build/logs/logFile.log (No such file or directory)

**Comment by tsauerwein** [comment]
This is a problem with you logging configuration, see https://github.com/camptocamp/c2cgeoportal/pull/2064.
