### ISSUE TITLE
Regarding License Print: GNU GPL / Framework BSD?

### ISSUE THREAD

**Issue by tilladams** [mapfish/mapfish-print#375]
Hi MapFish-Team,

We have an issue regarding the license. Downloading the MapFish Print-Zip, as License-Text the GNU GPL v3 is included. But the Mf-Print-Servlet is marked as part of the "MapFish Framework", which is, due to it's homepage licensed under BSD:
"MapFish is open source, and distributed under the BSD license."

Which license should/can a user choose (we have a customer, who'd prefer the BSD-license)?

Perhaps this is an issue for the PSC of MapFish (of which I am member)?

**Comment by tsauerwein** [comment]
Good question, I will check.

**Comment by tsauerwein** [comment]
Hi Till, sorry that it took that long to reply. MapFish Print 3 is released under GPL, but in fact we also prefer BSD and are willing to do the switch from GPL to BSD. We are now contacting all contributors to get the agreement for a license change. I will keep you posted.

**Comment by tsauerwein** [comment]
The new release 3.4.0 is now available under BSD.
