### ISSUE TITLE
Transparency on generated PDF

### ISSUE THREAD

**Issue by jgrocha** [mapfish/mapfish-print#386]
Hi,

I'm trying to put a semi-transparent text over the map. I set the element with some alpha value, like `backcolor="rgba(131, 255, 74, 0.52156866)"`. It works if I set the output to TIFF. If I set the output to PDF, the element became opaque.

![mapfish-print-report-with-transparency tiff](https://cloud.githubusercontent.com/assets/163681/13367726/8bb441ec-dcdc-11e5-9782-247122aad1f8.png)

I noticed that someone else also reported this transparency issue on the [jaspersoft community](http://community.jaspersoft.com/questions/897121/transparency-text-field), without any feedback.

Can it be a MapFish problem? I'm trying to read the sources to see the difference between TIFF and PDF outputs and I don't see anything that might be causing this opaque problem only in the PDF format.

**Comment by tsauerwein** [comment]
This is more an issue of JaserReports, we simply pass the template to JasperReports to create a PDF or TIFF.

It seems not to be supported, but you can create a semi-transparent image and put this image behind your text (as suggested in this [SO answer](http://stackoverflow.com/a/31921061/119937)). This is also why the scalebar or north-arrow can be transparent.

**Comment by jgrocha** [comment]
Thanks @tsauerwein for the feedback. I'll close the issue, since it seems like a JasperReport issue.
