### ISSUE TITLE
GeoServer 2.4.3 war is no longer available

### ISSUE THREAD

**Issue by tsauerwein** [mapfish/mapfish-print#388]
The war for GeoServer 2.4.3 which is used for the tests is no longer in the Maven repository:
https://repo.boundlessgeo.com/main/org/geoserver/web/web-app/2.4.3/

I quickly tested with a newer version (2.8.2 and 2.7.6) but the tests no longer pass.

**Comment by tsauerwein** [comment]
The ticket for GeoServer is here: https://osgeo-org.atlassian.net/browse/GEOS-7451

**Comment by tsauerwein** [comment]
It looks like we have to update GeoServer. I tested with GeoServer 2.8.2 (`gs-web-app:2.8.2`) but it doesn't work with the Jetty version (6.1.25) used by the Gradle plugin. There is a different Gradle plugin ([gretty](https://github.com/akhikhl/gretty)) which allows to use a newer version of Jetty (or even Tomcat), but I wasn't able to get it working with a quick try.

**Comment by pvalsecc** [comment]
Maybe we want to use docker for that... for example:
https://hub.docker.com/r/kartoza/geoserver/

**Comment by tsauerwein** [comment]
![dockerize](https://cloud.githubusercontent.com/assets/266474/13696836/5abb4896-e769-11e5-9cb4-ed61cf52c039.jpg)

**Comment by tsauerwein** [comment]
No, actually I would like to avoid to add a yet-another dependency on Docker. Also to make it easier to run the tests on Windows.
