### ISSUE TITLE
Merge layer graphics to reduce PDF size

### ISSUE THREAD

**Issue by tsauerwein** [mapfish/mapfish-print#391]
The `CreateMapProcessor` creates a graphic for each layer, saves the graphic as temporary PNG or SVG file, and embeds all image files into a sub-report. If a map has 10 layers the final PDF file will contain 10 images. The PDF file size can be reduced by merging the layer graphics.

Note that PNG and SVG files can not be merged, so that not all layer graphics can be merged into a single one.

E.g.:

```
PNG for layer 1       PNG for layer 1 + 2
PNG for layer 2 -->
SVG for layer 3       SVG for layer 3
PNG for layer 4       PNG for layer 4
```

**Comment by pmikla14** [comment]
Hi Tobias!

I found this entry today because our PDFs are quite big and take a long time to be generated... How can I activate the merge functionality? 

I found something like "mergeParams" in the docs, but I think this is something different..

Thank you!

**Comment by tsauerwein** [comment]
@pmikla14 This hasn't been implemented yet.

**Comment by pvalsecc** [comment]
We should make sure that base layers provided as JPG remains in the JPG format. Otherwise, the PDF is way bigger than needed.
