### ISSUE TITLE
Long running jobs are canceled even with regular status checks

### ISSUE THREAD

**Issue by olt** [mapfish/mapfish-print#404]
Long running print jobs are canceled with ``Job xx@xx is abandoned (no status check within the last 120 seconds)``, even if we poll ``/status/xx.json`` every second. (Tested with 3.4.0)

It looks like this bug was introduced with #249. ``LAST_POLL`` gets reset by ``ThreadPoolJobManager.isDone``, but [this call was removed](https://github.com/mapfish/mapfish-print/pull/249/files#diff-cfca81d0e459c6a536212899046cf285L244). The *done* status is now [computed in ``getStatus``, without calling ``isDone``](https://github.com/mapfish/mapfish-print/pull/249/files#diff-726ec4f8c61bea64583dc6c31f7ec255R384).

**Comment by tsauerwein** [comment]
Thanks for the good description! I prepared a fix in https://github.com/mapfish/mapfish-print/pull/405, could you test if it fixes the problem for you?

**Comment by olt** [comment]
:+1: Worked perfectly for a 10 minute print job. Thanks a lot!

**Comment by tsauerwein** [comment]
Nice, thanks for testing!
