### ISSUE TITLE
Compilation erroring with DynamicJasper & olap4j

### ISSUE THREAD

**Issue by pmauduit** [mapfish/mapfish-print#414]
While trying to launch gradle targets (`gradle eclipse` or `gradle dependencies`), I am encountering the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':core'.
> Could not resolve all dependencies for configuration ':core:runtimeCopy'.
   > Could not find ar.com.fdvs:DynamicJasper:5.0.0.
     Searched in the following locations:

[...]
   > Could not find org.olap4j:olap4j:0.9.7.309-JS-3.
```

Relying on mvnrepository.com, the v5.0.0 of DynamicJasper does not seem to be available anymore on the official repositories:
http://mvnrepository.com/artifact/ar.com.fdvs/DynamicJasper

This is probably due to the recent removal of the `dev.mapfish.org` server (which used to host a custom maven repository).

I see two possible approach to solve the issue:

1. Either copy the files on an accessible maven repo & modify the build.gradle so that the build process makes use of it
or
2. Upgrade to newer versions of these 2 libs

**Comment by pmauduit** [comment]
About the second error (with olap4j), this is not due to mapfish-print, but an upstream problem in jasperreports:

http://community.jaspersoft.com/questions/826431/failure-find-orgolap4jolap4jjar097309-js-3

**Comment by tsauerwein** [comment]
Thanks for reporting, Pierre! See https://github.com/mapfish/mapfish-print/pull/416
