### ISSUE TITLE
Legend for the bbox

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#415]
On the GetLegendGraphoce on a QGIS server we should add the BBOX parameter to have the legend only for the visible features.

**Comment by sbrunner** [comment]
And we should be able to add `LAYERTITLE=false`

It's possible that should be done in ngeo...

**Comment by sbrunner** [comment]
See also: http://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/ogc_server_support.html?highlight=server#extra-parameters-supported-by-all-request-types

**Comment by tsauerwein** [comment]
> It's possible that should be done in ngeo...

Yes, that should be done in ngeo.The legend processor doesn't know anything about WMS servers, it only downloads images given a list of URLs.
