### ISSUE TITLE
print-lib missing dependencies in the generated pom

### ISSUE THREAD

**Issue by pmauduit** [mapfish/mapfish-print#418]
See https://oss.sonatype.org/content/repositories/snapshots/org/mapfish/print/print-lib/3.5-SNAPSHOT/print-lib-3.5-20160530.101023-2.pom

**Comment by pvalsecc** [comment]
Is it still the case?

**Comment by pmauduit** [comment]
seems so, if I look at the pom from a more recent version:
https://oss.sonatype.org/content/repositories/snapshots/org/mapfish/print/print-lib/3.11-SNAPSHOT/print-lib-3.11-20170911.095225-1.pom

Still no dependencies defined, although if I decompile a random class in the Jar, I can find import references to spring.
