### ISSUE TITLE
very old version of org.json & wrongly generated JSON objects in info.json

### ISSUE THREAD

**Issue by pmauduit** [mapfish/mapfish-print#437]
Here:
https://github.com/mapfish/mapfish-print/blob/4fe38b76d149d0b61da8fec964acb1af0b9efcd0/core/build.gradle#L151

I stumbled upon an issue while integrating the MFprint in another java project which used a fairly more recent version of org.json lib. Here is the one I was using:

```
     <dependency>
       <groupId>org.json</groupId>
       <artifactId>json</artifactId>
      <version>20150729</version>
     </dependency>
```

This version refuses to add the same key twice when building a JSON Object, this lead me to the following stacktrace being dumped when asking for a info.json spec:

```
org.json.JSONException: Duplicate key "name"
    at org.json.JSONObject.putOnce(JSONObject.java:1317) ~[json-20150729.jar:na]
    at org.json.JSONWriter.key(JSONWriter.java:208) ~[json-20150729.jar:na]
    at org.mapfish.print.attribute.PrimitiveAttribute.printClientConfig(PrimitiveAttribute.java:80) ~[print-lib-3.5-SNAPSHOT.jar:na]
    at org.mapfish.print.config.Template.printClientConfig(Template.java:111) ~[print-lib-3.5-SNAPSHOT.jar:na]
```

Downgrading the lib to use the one from 2008 allowed me to generate the expected JSON document, but with repeated "name" keys in the output:

``` json
{"layouts":
  [
    {"name":"A4 portrait","attributes":
      [ {"name":"parcelle","name":"parcelle","type":"String"},
        {"name":"commune","name":"commune","type":"String"},
        {"name":"codeSection","name":"codeSection","type":"String"},{...
```

My understanding is that one should remove the following line:
https://github.com/mapfish/mapfish-print/blob/4fe38b76d149d0b61da8fec964acb1af0b9efcd0/core/src/main/java/org/mapfish/print/config/Template.java#L110

since the name key will be added in the following line with the `printClientConfig()` call.

**Comment by pvalsecc** [comment]
We are now using org.json:json:20180130`
