### ISSUE TITLE
Warning in the console

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#442]
I have this kind of warning:

```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
```

And the build don't works with OpenJDK 1.9 (9.0)

**Comment by tsauerwein** [comment]
> And the build don't works with OpenJDK 1.9 (9.0)

You might want to create a separate issue for that.

**Comment by sbrunner** [comment]
For me it's the same issue because it seam that the warning becomes an error ...

**Comment by tsauerwein** [comment]
Ok, I see. I guess we have to update the Gradle scripts and update some of our build files:
https://github.com/mapfish/mapfish-print/search?utf8=%E2%9C%93&q=512M

**Comment by sbrunner** [comment]
+1 :-)

**Comment by pvalsecc** [comment]
I guess this is not an issue anymore. I cannot find MaxPermSize anywhere

**Comment by sbrunner** [comment]
Thanks :-)
