### ISSUE TITLE
We should support the unit pt

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#447]
See also: https://github.com/camptocamp/ngeo/issues/1760

Concerned code: https://github.com/mapfish/mapfish-print/blob/master/core/src/main/java/org/mapfish/print/map/style/json/JsonStyleParserHelper.java#L384-L386

**Comment by tsauerwein** [comment]
GeoTools only accepts pixel values as font-size (see http://docs.geotools.org/latest/javadocs/org/opengis/style/Font.html#getSize--). Do you manually want to convert from pt to px?

**Comment by sbrunner** [comment]
Yes :-)

**Comment by sbrunner** [comment]
I just do a proposal :-)
