### ISSUE TITLE
"Standard" Subreports in Mapfish-Print

### ISSUE THREAD

**Issue by dmth** [mapfish/mapfish-print#451]
Hey folks,

normally I'd ask this on a mailing list or irc, but as http://lists.mapfish.org/cgi-bin/mailman/listinfo appears to be down and the irc-channel is empty, I decided to misuse the bugtracker for my question. Please point me to the appropriate direction, if there is any.

I need to use mapfish-print 3 in order to create reports. Unfortunately those are not maps, but "classic" reports which include multiple nested subreports. In Jaspersoft Studio, I can use a JsonDatasource to create these reports and can also access this datasource from the subreports, by providing it as a subDataSource, like:

```
((net.sf.jasperreports.engine.data.JsonDataSource)$P{REPORT_DATA_SOURCE}).subDataSource("MyNestedThing")
```

Unfortunately I fail to model this in mapfish-print. From the Documentation [1] I cannot figure how to create a subreport and how it is possible to add a datasource or even a subDataSource.

I've seen the entries "What is a subreport for?" and "How do I add/remove a Subreport?" in the FAQ [2]
But I'm not sure if this also means that it's not possible at all to use "standard" subreports,  which are not a north-arrow, legend, or a table.

Best Regards and thanks in Advance

Dustin

[1] http://mapfish.github.io/mapfish-print-doc/configuration.html
[2] http://mapfish.github.io/mapfish-print-doc/jasperreports.html

**Comment by tsauerwein** [comment]
Hi Dustin!

> normally I'd ask this on a mailing list or irc, but as http://lists.mapfish.org/cgi-bin/mailman/listinfo appears to be down and the irc-channel is empty, I decided to misuse the bugtracker for my question. Please point me to the appropriate direction, if there is any.

Where did you find the link to this old mailing-list? And I didn't event know that there is an IRC channel... :O The new mailing-list is here: https://groups.google.com/forum/#!forum/mapfish-print-users

About your question: What you are describing is possible, but currently only with a database as datasource. The *problem* is that MapFish Print has to create the datasource for the JasperReports template, and currently only JDBC database connections are supported.

This would be the basic configuration in the `config.yaml`:

```
    A4 portrait: !template
        reportTemplate: A4_Portrait.jrxml
        jdbcUser: "www-data"
        jdbcPassword: "www-data"
        jdbcUrl: "jdbc:postgresql://localhost:5432/test"
```

Then in your template you can use the created datasource:

```
	<queryString>
		<![CDATA[select id, name, address, phone, hours from mfp.restaurants where id = $P{id}]]>
	</queryString>
	<field name="id" class="java.lang.Integer"/>
	<field name="name" class="java.lang.String"/>
	<field name="address" class="java.lang.String"/>
	<field name="phone" class="java.lang.String"/>
	<field name="hours" class="java.lang.String"/>
...
	<detail>
		<band height="209" splitType="Stretch">
			<textField>
				<reportElement x="0" y="0" width="340" height="23" uuid="b00afc01-efec-4c59-98a7-7416c100f0b3"/>
				<textElement>
					<font size="16" isBold="true" isItalic="true"/>
				</textElement>
				<textFieldExpression><![CDATA[$F{name}]]></textFieldExpression>
			</textField>
```

If you want to use the datasource in a sub-report, you can pass the connection to the sub-report template:
```
			<subreport>
...
				<connectionExpression><![CDATA[$P{REPORT_CONNECTION}]]></connectionExpression>
				<subreportExpression><![CDATA["MySubreport.jasper"]]></subreportExpression>
			</subreport>
```

**Comment by dmth** [comment]
Hi Tobias,

thank you very much for your answer.

> Where did you find the link to this old mailing-list? And I didn't event know that there is an IRC channel... :O The new mailing-list is here: https://groups.google.com/forum/#!forum/mapfish-print-users

I think it's a legacy of: mapfish.org ;-)

>  What you are describing is possible, but currently only with a database as datasource. The problem is that MapFish Print has to create the datasource for the JasperReports template, and currently only JDBC database connections are supported.

I take that as good and bad news at the same time.
Can you roughly evaluate the efforts required to extend mapfish-print with a JSON-Datasource?


BR
Dustin

**Comment by dmth** [comment]
Hi,

Tobias provided an example [1] which helps us very much. Thank you!

However, I wonder how this example can be extended in order to work with "missing" data, like:

``` 
{
    "layout": "A4 portrait",
    "outputFormat": "pdf",
    "attributes": {
        "title": "Soils",
        "comments": "...",
        "soils": [{
            "soilName": "Soil A"
        }, {
            "soilName": "Soil B",
            "profiles": [
	            {
	            	"profileName": "Profile B A",
	            	"horizons": [{
	                    "horizonName": "Horizon B A A"
	                 }]
	            }, {
	            	"profileName": "Profile B B",
	            	"horizons": [{
	                    "horizonName": "Horizon B B A"
	                 }]
	            }
            ]
        }]
    }
}
```
[1] https://github.com/mapfish/mapfish-print/compare/master...tsauerwein:nested-datasources

**Comment by tsauerwein** [comment]
Providing an empty list does not work?

```
"soils": [{
            "soilName": "Soil A",
            "profiles": []
        },
```

**Comment by dmth** [comment]
Providing an empty list results in a
```
Error while processing request:
com.vividsolutions.jts.util.AssertionFailedException: The following parameters are declared in A4_Portrait.jrxml.  The class attribute in the template xml does not match the class of the actual object.
Either change the declaration in the jasper template or update the configuration so that the parameters have the correct type.

	* profileDatasource : net.sf.jasperreports.engine.JREmptyDataSource expected type: net.sf.jasperreports.engine.data.JRMapCollectionDataSource
```

If no profiles are provided at all, 
```
Error while processing request:
org.mapfish.print.PrintException: Missing required attribute: profiles
``` 
is raised.

**Comment by tsauerwein** [comment]
The type in the template could maybe be changed to [net.sf.jasperreports.engine.JRDataSource](http://jasperreports.sourceforge.net/api/net/sf/jasperreports/engine/JRDataSource.html)? `JREmptyDataSource` and `JRMapCollectionDataSource` both implement this interface.

**Comment by dmth** [comment]
Using a JRDataSource instead of JRMapCollectionDataSource works,

**Comment by tsauerwein** [comment]
Closing this issue because the question seems to be answered. @dmth, feel free to reopen or to open a new issue in case.
