### ISSUE TITLE
Printing in higher DPI does not work for WMTS layers

### ISSUE THREAD

**Issue by tsauerwein** [mapfish/mapfish-print#459]
The TileMatrix of a WMTS layer is [selected depending on the scale](https://github.com/mapfish/mapfish-print/blob/0ef26fc/core/src/main/java/org/mapfish/print/map/tiled/wmts/WMTSLayer.java#L70-L77). Because in this case the scale is the same when printing with DPI 100 or DPI 300, the same TileMatrix is always used. So, WMTS layers can not be printed in a higher resolution.

**Comment by pvalsecc** [comment]
You want to add a scaleRatio configuration parameter or something?

**Comment by tsauerwein** [comment]
I tend to say to no additional `scaleRatio` parameters should be required. It should work the same way as for example with XYZ tiles (and also in v2?).
