### ISSUE TITLE
maxDpi not described

### ISSUE THREAD

**Issue by stan4gis** [mapfish/mapfish-print#476]
`!map` attribute `maxDpi` is listed in doc by not discribed (MapFish Print v3 master doc)

**Comment by tsauerwein** [comment]
Would you be able to contribute a PR adding the missing docs? The documentation is extracted from the Java comments, for example for `maxDpi` from here: https://github.com/mapfish/mapfish-print/blob/9aa21eddebb84afbbd01987598221451115192da/core/src/main/java/org/mapfish/print/attribute/map/GenericMapAttribute.java#L76

**Comment by stan4gis** [comment]
Unfortunately I'm a very beginner on github. 
And the java comment "The json key for the max DPI value in the client config." doesn't explain me a lot...
