### ISSUE TITLE
A0 pdf - missing map image, pdf generated, no error

### ISSUE THREAD

**Issue by ochriste** [mapfish/mapfish-print#544]
when trying to generate an A0 sized pdf, the pdf is generated without error, but the map image is missing (i.e. not included in the pdf returned)

**Comment by sbrunner** [comment]
Can you provide a non working example (config.yaml and spec.json)?
I just do a test and it was working ...

**Comment by ochriste** [comment]
[mapfish-print-report(4).pdf](https://github.com/mapfish/mapfish-print/files/993467/mapfish-print-report.4.pdf)
[config.yaml.txt](https://github.com/mapfish/mapfish-print/files/993470/config.yaml.txt)
[spec.json.txt](https://github.com/mapfish/mapfish-print/files/993473/spec.json.txt)
file attached

**Comment by sbrunner** [comment]
It shouldn't ...

**Comment by sbrunner** [comment]
Does your mapserver accept a request with a width bigger than 11000 px?

**Comment by sbrunner** [comment]
11713x8076 in my try ...

**Comment by sbrunner** [comment]
We probably should catch better the WMS server error...

**Comment by sbrunner** [comment]
With version 1.1.1:
return mime type: application/vnd.ogc.se_xml;charset=UTF-8
With version 1.3.0:
return mime type: text/xml;charset=UTF-8

On success:
return mime type: image/png

**Comment by ochriste** [comment]
I can copy the request done by Mapfish Print as logged in catalina.log and do a curl request without error. the image recovered is ok.
it's is just Mapfish Print not including that image in the pdf, but I dont know  why

**Comment by ochriste** [comment]
here is the print log
[print_log.txt](https://github.com/mapfish/mapfish-print/files/993699/print_log.txt)

the request done by Mapfish Print is 

http://127.0.0.1/och/wsgi/mapserv_proxy?TRANSPARENT=true&MAP_RESOLUTION=254&BBOX=557629.99999896%2C138086.99984298%2C565799.99999896%2C148902.99984298&CACHE_VERSION=f003da033e444e43888391fd917721e0&VERSION=1.1.1&FORMAT=image%2Fpng&SERVICE=WMS&HEIGHT=10816&USERNAME=xxx&REQUEST=GetMap&LAYERS=cs_foret&STYLES=&SRS=EPSG%3A21781&WIDTH=8170

with curl:

curl -H "host: preprod.cartoriviera.ch" -o test3.png "http://127.0.0.1/och/wsgi/mapserv_proxy?TRANSPARENT=true&MAP_RESOLUTION=254&BBOX=557629.99999896%2C138086.99984298%2C565799.99999896%2C148902.99984298&CACHE_VERSION=f003da033e444e43888391fd917721e0&VERSION=1.1.1&FORMAT=image%2Fpng&SERVICE=WMS&HEIGHT=10816&USERNAME=xxx&REQUEST=GetMap&LAYERS=cs_foret&STYLES=&SRS=EPSG%3A21781&WIDTH=8170"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1702k    0 1702k    0     0   527k      0 --:--:--  0:00:03 --:--:--  527k

and the image is:

![test3](https://cloud.githubusercontent.com/assets/138678/25960096/372dc518-3676-11e7-9c1b-a95781b31297.png)

please note this test was done with the portrait layout, not the landscape layout, but the problem is the same

**Comment by ochriste** [comment]
mapfile MAXSIZE is set at 12000

**Comment by sbrunner** [comment]
Finally it was a hidden out of memory error... => we needs 2G of xmx for that :-)
