### ISSUE TITLE
Log lvl defaults to DEBUG

### ISSUE THREAD

**Issue by eftas-apps** [mapfish/mapfish-print#591]
Hi,

I just installed the latest mapfish in a docker container. It's working fine. Only thing is that the logs are spamming all the json data and DEBUG logs by default. 

I tryed editing the logback.xml and also the shell-default-log.xml without any effect. Am I missing anything? 

Seems like org.springframework is creating all the log info. Although clearly stated in logback.xml that the log lvl is WARN

**Comment by sbrunner** [comment]
With version do you use?

**Comment by eftas-apps** [comment]
Sorry, my fault. Forgot to mention it. 
I'm using 3.10.2

**Comment by sbrunner** [comment]
Normally with this release we have less unneeded logs, by dfaut you should have only the WARN logs...
To don't have the json logs you can add:
```xml
<logger name="org.mapfish.print.servlet.spec" level="OFF" />
```

**Comment by eftas-apps** [comment]
already tried that. But that doesn't help either. 
Just to clarify I need to edit the logback.xml in /WEB-INF/classes, right? 

I tried all these options 

> 
    <logger name="org.mapfish" level="WARN" />
    <logger name="org.mapfish.print.output.ValuesLogger" level="OFF" />
    <logger name="org.mapfish.print.servlet.MapPrinterServlet" level="OFF" />
    <logger name="org.mapfish.print.servlet.OldAPIMapPrinterServlet" level="OFF" />
    <logger name="org.mapfish.print.servlet.spec" level="OFF" />
    <logger name="com.codahale" level="WARN" />
    <logger name="org.springframework" level="ERROR" />
    <logger name="org.apache" level="WARN" />
    <logger name="org.hibernate" level="WARN" />

    <root level="INFO">
        <appender-ref ref="standardOut" />
    </root>
</configuration>

**Comment by sbrunner** [comment]
Yes :-)

**Comment by eftas-apps** [comment]
Unfortunately mapfish does not seem to be very impressed. 
It still prints everything in the logs. Even after restarting several times.

**Comment by pvalsecc** [comment]
Do you use the official image?

The camptocamp/mapfish_print docker image is designed to be configured via environment variables and the file configuring that is in `${CATALINA_HOME}/conf/logback-custom.xml`.

By default, the environment variables are set like that:
https://github.com/mapfish/mapfish-print/blob/master/core/build.gradle#L326-L330

**Comment by eftas-apps** [comment]
Thanks pvalsecc, 

that did the trick! We had mounted the config files before. But via environment variables if works. 
Is there also a way to change the values in `mapfish-spring.properties`?

**Comment by pvalsecc** [comment]
If you set the CATALINA_OPTS environment variable, you can pass additional parameters to java. Part of them, you can pass stuff like `-DthreadsParallelProcessors=50`. I'd recommend a decent `-Xmx` as well.

I'm updating the doc with some information I've put in this ticker and some more:
https://github.com/mapfish/mapfish-print/pull/592

**Comment by pvalsecc** [comment]
I think all the issues are resolved, here. Closing.

**Comment by eftas-apps** [comment]
Yes, thanks! Solved my problems!
