### ISSUE TITLE
Sample config.yaml with all available options

### ISSUE THREAD

**Issue by Alexandre27** [mapfish/mapfish-print#600]
It would be useful to have in the docs a sample config.yaml with all the available options like the one available [here](http://www.mapfish.org/doc/print/configuration.html). In spite of the usefulness of the examples provided it is hard to figure the full structure of the yaml as each example includes only certain sections of it. For instance keys like `throwErrorOnExtraParameters` and `transparentTileErrorColor` only appear in the examples and certain configurations and processors appear both at top level and nested.

**Comment by Alexandre27** [comment]
I already read it and looked in the workshop files too, but some things are not available there like for example in the map attribute the `maxDpi` isn't documented as required and i cannot find the available options for the `zoomLevelSnapStrategy`, so it makes the configuration process a little bit of trial and error. Are all the different config possibilities available in the examples? Is there some tutorial/lecture that you recommend looking up?

**Comment by fegyi001** [comment]
The provided config.yaml doesn't contain all available options at all. I also wander whether there is one anywhere. 
For what I'm actually looking for is the correct way to set the overview map rectangle border and fill color. All the documentation says is that: "The style name of a style to apply to the bbox rectangle of the original map during rendering. The style name must map to a style in the template or the configuration objects."

I'm a newbie to Mapfish v3 (I used v2 quite a lot).

Could you help me out? Thanks in advance!

**Comment by pvalsecc** [comment]
You have a lot of examples there:
https://github.com/mapfish/mapfish-print/tree/master/examples/src/test/resources/examples

The doc is not perfect, but it is there:
http://mapfish.github.io/mapfish-print-doc/index.html

For example `maxDpi` is "documented" in there:
http://mapfish.github.io/mapfish-print-doc/attributes.html#!map

As its name is quite self explanatory, I guess it doesn't need any explanation. And you have a link to an example in the docs.
