### ISSUE TITLE
The build templates mixed

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#603]
The build templates are stored in `/srv/tomcat/tomcat1/temp/mapfish-print/<print_apps>/jasper-bin/<template-name>.jasper`.
This mean that two tomcat webapps share the same templates...

**Comment by pvalsecc** [comment]
That is set here: https://github.com/mapfish/mapfish-print/blob/cb4f81bd5a7a888c0e1017362f4c1ab2718a576e/core/src/main/resources/mapfish-spring.properties#L2

**Comment by sbrunner** [comment]
:-(

**Comment by pvalsecc** [comment]
OK, found a trick. wait for the patch...
