### ISSUE TITLE
Too large halo around text

### ISSUE THREAD

**Issue by ger-benjamin** [mapfish/mapfish-print#605]
Previous discussion here: https://github.com/camptocamp/ngeo/issues/3065#issuecomment-344189374

Concerns MapFish Print v3.10.3 (at least)

The halo around a text is too big for the given value if this value is in pixel. If the unit used is not "pixel", that should be precised in the documentation.

Here some comparison:

The OpenLayers ("on web") result (stroke are in pixel, 1 to 5):
![selection_050](https://user-images.githubusercontent.com/1792111/32771172-2b025076-c922-11e7-9b0a-aabdd1ee01cc.png)

The MapFish Print ("on pdf") result:
![selection_053](https://user-images.githubusercontent.com/1792111/32771209-54c815ee-c922-11e7-906b-2ed0be5974e4.png)

And the report spec:
![selection_054](https://user-images.githubusercontent.com/1792111/32771165-26445836-c922-11e7-9e38-6e1d8c651d38.png)

(Note: With my search for an already existing issue concerning with the same purpose, I see this issue: https://github.com/mapfish/mapfish-print/issues/72 I think we can close it. No ?)

**Comment by pvalsecc** [comment]
The print's behavior here is correct. If you ask for a halo with a **radius** of 5px, you get a halo with a **radius** of 5px. See https://github.com/camptocamp/ngeo/issues/3065#issuecomment-348916931

**Comment by ger-benjamin** [comment]
Thanks @pvalsecc
