### ISSUE TITLE
Features in GeometryCollection not Printed Correctly

### ISSUE THREAD

**Issue by marionb** [mapfish/mapfish-print#617]
When printing a GeometryCollection MultiPoints do not get printed correctly. The placement of the points is wrong and not all of the points get printed. For every line string/MultiLineString and Polygon/MultiPolygon there seems to be an extra point being printed.

Below is an example of the json I used and an image of the print result output I get. The green points come from the points defined out side the GeometrCollection, the red points I don't know where they come from.

    {
    	"layout": "A4 Landscape",
    	"outputFormat": "pdf",
    	"attributes": {
    		"title": "Amtliche Vermessung Gde",
    		"subtitle": "",
    		"printScale": "1'000",
    		"logo": "http://www.entw.geoportal.ch/api/primaryarea/logo/1",
    		"centerCoordinate": "2'739'011, 1'249'914",
    		"epoch": "",
    		"map": {
    			"projection": "EPSG:2056",
    			"dpi": 100,
    			"rotation": 0,
    			"center": [2739011, 1249914],
    			"scale": 1000,
    			"layers": [{
    					"type": "geojson",
    					"name": "search",
    					"geoJson": {
    						"type": "FeatureCollection",
    						"features": [{
    								"type": "Feature",
    								"geometry": {
    									"type": "GeometryCollection",
    									"geometries": [{
    											"type": "MultiLineString",
    											"coordinates": [[[2739024.16384275, 1249955.99645933], [2739014.72195189, 1249952.38854164], [2739005.37306451, 1249947.71461492], [2738991.35021414, 1249945.37775968], [2738983.11429912, 1249944.70984995], [2738974.433389, 1249943.93094453], [2738963.27549946, 1249944.15907527]]]
    										}, {
    											"type": "MultiPoint",
    											"coordinates": [[2738980.061, 1249914.028], [2739019.219, 1249917.041], [2739057.748, 1249913.638], [2739066.366, 1249930.744]]
    										}
    									]
    								},
    								"properties": {
    									"type": "GeometryCollection"
    								}
    							},{
    								"type": "Feature",
    								"geometry": {
    									"type": "MultiPoint",
    									"coordinates": [[2738980.061, 1249914.028], [2739019.219, 1249917.041], [2739057.748, 1249913.638], [2739066.366, 1249930.744]]
    								},
    								"properties": {
    									"type": "MultiPoint"
    								}
    							}
    						]
    					},
    					"renderAsSvg": false,
    					"style": {
    						"version": "2",
    						"[type = 'MultiLineString']": {
    							"symbolizers": [{
    									"type": "line",
    									"strokeLinecap": "butt",
    									"strokeColor": "rgb(10, 130, 210)",
    									"strokeWidth": 2
    								}
    							]
    						},
    						"[type = 'MultiPolygon']": {
    							"symbolizers": [{
    									"type": "line",
    									"strokeLinecap": "butt",
    									"strokeColor": "rgb(10, 130, 210)",
    									"strokeWidth": 2
    								}, {
    									"type": "polygon",
    									"strokeLinecap": "butt",
    									"strokeWidth": 1,
    									"fillOpacity": 0,
    									"strokeColor": "rgb(10, 130, 210)"
    								}
    							]
    						},
    						"[type = 'Polygon']": {
    							"symbolizers": [{
    									"type": "line",
    									"strokeLinecap": "butt",
    									"strokeColor": "rgb(10, 130, 210)",
    									"strokeWidth": 2
    								}, {
    									"type": "polygon",
    									"strokeLinecap": "butt",
    									"strokeWidth": 1,
    									"fillOpacity": 0,
    									"strokeColor": "rgb(10, 130, 210)"
    								}
    							]
    						},
    						"[type = 'Point']": {
    							"symbolizers": [{
    									"type": "point",
    									"graphicName": "circle",
    									"strokeColor": "rgb(10, 130, 210)",
    									"strokeWidth": 1,
    									"graphicOpacity": 0,
    									"pointRadius": 3,
    									"fillColor": "rgb(10, 130, 210)"
    								}
    							]
    						},
    						"[type = 'MultiPoint']": {
    							"symbolizers": [{
    									"type": "point",
    									"graphicName": "circle",
    									"strokeColor": "rgb(10, 180, 20)",
    									"strokeWidth": 1,
    									"graphicOpacity": 0,
    									"pointRadius": 3,
    									"fillColor": "rgb(0, 255, 0)"
    								}
    							]
    						},
    						"[type = 'GeometryCollection']": {
    							"symbolizers": [{
    									"type": "point",
    									"graphicName": "circle",
    									"strokeColor": "rgb(255, 0, 0)",
    									"strokeWidth": 1,
    									"graphicOpacity": 0,
    									"pointRadius": 3,
    									"fillColor": "rgb(255, 0, 0)"
    								}, {
    									"type": "line",
    									"strokeLinecap": "butt",
    									"strokeColor": "rgb(10, 10, 210)",
    									"strokeWidth": 2
    								}
    							]
    						}
    					}
    				}
    			]
    		}
    	}
    }

![requestdata](https://user-images.githubusercontent.com/1460598/33608101-bc77afae-d9c3-11e7-94db-6719a29dc913.png)

**Comment by pvalsecc** [comment]
What version?

**Comment by marionb** [comment]
I get behaviour this with the new version you just released MFP 3.11.1
(Sorry, I thought for some odd reason that it was intuitively clear)

**Comment by pvalsecc** [comment]
Please try the latest: 3.11.3

**Comment by marionb** [comment]
With 3.11.3 it is still the same result, nothing changed.

**Comment by pvalsecc** [comment]
The print uses SLD behind the scene and you cannot do such a thing with SLD. Here is some doc that applies to your situation:
http://docs.geoserver.org/maintain/en/user/styling/sld/tipstricks/mixed-geometries.html

**Comment by marionb** [comment]
Thanks!
