### ISSUE TITLE
Geoserver print module issue with WMS layers

### ISSUE THREAD

**Issue by jcb81** [mapfish/mapfish-print#623]
Hello everyone,

I searched for many hours for my issue, I hope I'll get some answers here.

The context : I installed Geoserver (2.11.1) and configured some layers coming from stores "Oracle NG" and "WMS". I also installed the print module "Mapfish" to be able to send print request from a web application to generate map reports.

After many searches, I can now configure well the "config.yaml" file to configure the print layouts, and I understand how works the GET and POST http print requests and parameters.

Here is my issue : the print request work well with layers coming from "Oracle NG" store, but not the ones from the "WMS" store. When I download the generated PDF, I get my report with a blank map and an exception message in a little yellow box near the map area : "java.io.IOException: The byte array is not a recognized imageformat."

![mapfish_print_error_1](https://user-images.githubusercontent.com/34311617/33669265-3daee70c-daa2-11e7-8cf5-afe5458b06a2.PNG)
![mapfish_print_error_2](https://user-images.githubusercontent.com/34311617/33669272-4463024a-daa2-11e7-96ca-bea7cf012e09.PNG)

Here is a working request : http://localhost:9100/geoserver/pdf/print.pdf?spec={outputFilename:'print-${yyyyMMddHHmmss}',layout:'MY_MAP_LAYOUT',pages:[{center:[88861.938477485,100786.976035025],scale:10000,rotation:0}],dpi:75,units:'m',srs:'EPSG:2169',layers:[{baseURL:'http://localhost:9100/geoserver/wms',type:'WMS',layers:['WS:ORACLE_LAYER'],format:'image/png'}]}

Here is a NOT working request : http://localhost:9100/geoserver/pdf/print.pdf?spec={outputFilename:'print-${yyyyMMddHHmmss}',layout:'MY_MAP_LAYOUT',pages:[{center:[88861.938477485,100786.976035025],scale:10000,rotation:0}],dpi:75,units:'m',srs:'EPSG:2169',layers:[{baseURL:'http://localhost:9100/geoserver/wms',type:'WMS',layers:['WS:WMS_LAYER'],format:'image/png'}]}

Only the layer asked changes in the parameters.

The only thing I found for now is about authentification issue on WMS layers, but my WMS layers don't have any authentification, they can be reached as it.

Is anyone here already had this issue ? Or have an explanation on what I'm doing wrong ?
Any help will be really appreciated !

**Comment by pvalsecc** [comment]
Look at the print logs. Look for the URL the print uses for reading your WMS layer. Then try to do the query manually (with curl or wget) and look at the result. Maybe it will answer your question.

**Comment by jcb81** [comment]
Indeed.
The exception in the report was coming from that the http request was returning an XML response, and as you say, I can reproduce it with the logs of Geoserver. In my case, it was an issue about the asked image format (image/jpg not supported, changed to image/png), then it was about a width limitation. I changed the associated map file of the called WMS to set MAXSIZE at 4096 for example, and all works well now.
Thank you very much.
