### ISSUE TITLE
Mapfish print module : sending a POST request, then changed in GET ?

### ISSUE THREAD

**Issue by jcb81** [mapfish/mapfish-print#628]
Hello everyone, 

I have an issue with the size of my print request. 
I send a POST http request because I know that the spec parameter can be 
really big (I have a custom parameter CQL_FILTER to filter some layers to 
print). The POST request is well sent with "/geoserver/pdf/create.json". 
When I check the generated PDF, I get an empty map with the following error 
near the zone of the map : "Error java.io.IOException : Error (status=414) 
while reading the image from http://.......(the rest of the big url)...". 

When I check the log file of GeoServer, I see the same error : "ERROR 
[print.PDFUtils] - Server returned an error for http://.....(the rest of the 
big url)... : Request-URI Too Large" 

I understand the error, URI too long, but why my POST request is finally 
converted in GET request to retrieve the image of my report ? Why doesn't it 
stay in POST request ? Do I have to configure something in the print plugin 
? 

Any help appreciated. 

Kind regards, 

JCB

**Comment by pvalsecc** [comment]
You POST request is sent to GeoServer, then it's GeoServer choosing to do a GET to MapFish Print. Therefore, this ticket should be open against GeoServer, not MapFish Print. I'll close it, here.

**Comment by Feofilakt** [comment]
It's funny, in GS they had closed this issue for the same reason: https://osgeo-org.atlassian.net/browse/GEOS-8480?focusedCommentId=78596&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-78596
