### ISSUE TITLE
Basemaps are not printed when low zoom levels

### ISSUE THREAD

**Issue by Mieczyslawski** [mapfish/mapfish-print#630]
When I'm trying to print basemaps from Stamen (http://maps.stamen.com/) I'm receiveing error (on console) and red tiles on pdf. It happens only when zoom level is very low. Similar issue is happening for basemap tiles from https://server.arcgisonline.com.

Here is my request json:

      "map":{  
         "center":[  
            -9120818.708283924,
            4426957.752657155
         ],
         "dpi":"72",
         "layers":[         
          
            {  
               "baseURL":"http://stamen-tiles-a.a.ssl.fastly.net/toner/",
               "imageFormat":"png",
               "type":"OSM"
            }
         ],
         "projection":"EPSG:900913",
         "rotation":0,
         "scale":7536854
      }

and on console I'm receiving multiple errors like:

        Status: 503
        outMessage: Service Unavailable
        11:18:09.169 [ForkJoinPool-2-worker-2] ERROR o.m.print.map.tiled.CoverageTask -
        Error making tile request: http://stamen-tiles-a.a.ssl.fastly.net/toner/05/9/12.png

I beleive that issue is caused because request for the tiles from stamen server is not formed correctly in mapfish - it should be:
        http://stamen-tiles-a.a.ssl.fastly.net/toner/5/9/12.png
instead of:
        http://stamen-tiles-a.a.ssl.fastly.net/toner/05/9/12.png

Mapfish is adding "0" for {z} parameter in case when it is only one digit - this is why it is not working with low zoom levels, but for higher zooms it works fine.

Can you please fix this?

**Comment by pvalsecc** [comment]
The code doing that: https://github.com/mapfish/mapfish-print/blob/cd3449f3c4b8dad0414ae8eb307cde29dd05f2d9/core/src/main/java/org/mapfish/print/map/tiled/osm/OsmLayer.java#L98

Looking at URLs used to fetch tiles on http://www.openstreetmap.org/, the zoom level is not prepended a 0 when <10. I don't understand why we are doing that and I'm a bit afraid to change that.

@sbrunner, an opinion on that?

**Comment by sbrunner** [comment]
Effectively there isn't any reason of that ...
