### ISSUE TITLE
dnsMatch fails in IP-address based load-balancer environments

### ISSUE THREAD

**Issue by awaterme** [mapfish/mapfish-print#645]
Hi,

we are using dnsMatch to whitelist the allowed targets for WMS requests.

In our case the domain name points to a load balancer. The load balancer potentially uses different numeric IP addresses. The active IP address changes over time. I dont have more information regarding this load balancer. I don't know if this is a common practice, or if "load balancer" is even the right term, maybe it is more kind of a high availability device. I don't know. Fact is: The numeric IP changes.

Problem: mapfish-print seems to resolve the configured domain name into a list of numeric IP adresses (maybe on startup?). If the numeric IP changes over time mapproxy denies the access, which is not desired.

If I am right, I find this implementation of matching domain names by the numeric IP somewhat unexpected. Is this to support users providing both, the numeric IP or the domain name in case of a dnsMatch? 

I'd like to suggest an additional domain name string comparison. I currently do not see any disadvantage of a string comparision.

**Comment by pvalsecc** [comment]
Yes, the hostname is resolved only once when the config is read:
https://github.com/mapfish/mapfish-print/blob/release/3.11.3/core/src/main/java/org/mapfish/print/processor/http/matcher/DnsHostMatcher.java#L81

But if we don't do that and we resolve the address for each query this may be quite slow... what do you suggest we do?

**Comment by awaterme** [comment]
What do you think about extending the matcher by additionally performing a simple string comparison: domain name from the request parameter vs configured domain name.
That should actually work, shouldn't it?
If that not feasible for all cases maybe introduce a flag in dnsMatch to de-/activate it?

**Comment by pvalsecc** [comment]
Yes, doable. But I'd rather have a new matcher `HostnameMatcher`. And document in DnsHostMatcher when the DNS resolution is performed...

**Comment by awaterme** [comment]
Hi Patrick, that sounds good to me.

**Comment by awaterme** [comment]
Hi, 
I'd like to come back to this issue, because we need a solution for our customer.
Shall I prepare a pull request for a `HostnameMatcher`?
Do you want to given me any guidelines or hints upfront?
Best regards,
Andreas

**Comment by pvalsecc** [comment]
> Shall I prepare a pull request for a HostnameMatcher?

Yes, please.

> Do you want to given me any guidelines or hints upfront?

Look at how the DnsHostMatcher is implement and Include at least one unittest.

**Comment by awaterme** [comment]
Hi,
I have some difficulties making the HostnameMatcher work.
I have the impression that in the current head revision on master, the matchers are not invoked, for our configuration. They have been invoked with MFP 3.7.0.

Fragment of our config:

```
    processors:
    - !reportBuilder
      directory: '.'
    - !createMap
      inputMapper: {rMap: map}
      outputMapper: {mapSubReport: rMapSubReport}
    - !createMap
      inputMapper: {scalebarMap: map}
      outputMapper: {mapContext: scalebarMapContext}
    - !createScalebar
      inputMapper: { scalebarMapContext: mapContext }
    - !createNorthArrow
      inputMapper: {
       rMap: map,
       northArrowDef: northArrow
      }
      outputMapper: {
       northArrowSubReport: northArrowSubReport
      }
    - !configureHttpRequests
       httpProcessors:
         - !mapUri
           mapping: {
            "(.*)/geoserver(.*)" : "http://myhost/geoserver$2",
            "(.*)/2nd(.*)" : "http://myhost:80/2nd$2"
           }
         - !forwardHeaders
           headers: [user_id, roles]
         - !restrictUris
           matchers: 
           - !localMatch {}
           - !dnsMatch
             host: myhost
             port: 80
```

What I see: In 3.7.0, [WMSLayer.loadImage()](https://github.com/mapfish/mapfish-print/blob/7852cc5f800e2dc78180489623822cdcb330d914/core/src/main/java/org/mapfish/print/map/image/wms/WmsLayer.java#L73) initiated a MapUriProcessor$1.createRequest(...). That code called the matchers.

This has been refactored and is not called anymore, AFAICS. Maybe [RestrictUrisProcessor$1](https://github.com/mapfish/mapfish-print/blob/ff141efe767730c040c62087c7f7c0a508d8528a/core/src/main/java/org/mapfish/print/processor/http/RestrictUrisProcessor.java#L82) is used now, from somewhere else, and there is not matching performed (see inline comment)?

I don't know for sure; as I don't know the overall concepts I can't find the issue in time.
Could you have a quick look, please?

**Comment by pvalsecc** [comment]
No, the processor ordering is important. You have to put your configureHttpRequests first.

**Comment by awaterme** [comment]
Hi,
yes, changing the ordering solved it. I have now prepared pull request #648. Please check if you are happy with it. 

Regarding the ordering: As you mentioned it I found it in the "breaking changes" document. Maybe it would be worth to mention this more prominent, as this doesn't show up as an error but is just an dead security configuration.

Is there already a date for the next release?

Do you need anything else? CLA?

Best regards,
Andreas

**Comment by pvalsecc** [comment]
I'll do a release 3.11.x in the next couple of days.

**Comment by pvalsecc** [comment]
OK, 3.12.0 released. It will take a few hours/days to show up in the maven repos, but the docker image is already there and you can download the war: http://central.maven.org/maven2/org/mapfish/print/print-servlet/3.12.0/

**Comment by awaterme** [comment]
Great, thank you very much!
