### ISSUE TITLE
Remove the Debian package

### ISSUE THREAD

**Issue by pvalsecc** [mapfish/mapfish-print#657]
We already generate the WAR which is very easy to install in debian. As far as we (@sbrunner, @fredj and @pvalsecc) know, this package is not used.

Plus, while at it, fix docs/src/main/resources/templates/download.html to include the docker image.

**Comment by dkastl** [comment]
Additionally, when you uninstall the Debian package, and if there is no other content in `/srv` directory, then it seems to remove the `/srv` directory as well.

**Comment by pvalsecc** [comment]
This has been done in #714
