### ISSUE TITLE
Feature request: JSON datasource

### ISSUE THREAD

**Issue by romanzoller** [mapfish/mapfish-print#665]
**Context**

A client would like to use [data that is already available in a certain JSON structure](https://github.com/romanzoller/mfp-json/blob/0fb4902ae3bf70e61886c2cc7c57d9a9d8e71b10/requestData.json#L5-L53) to render a report similar to the following:

![image](https://user-images.githubusercontent.com/23193956/37652740-75c79c04-2c34-11e8-84b8-4f9771aea413.png)

**Requested Feature**

By [stringifying the JSON](https://github.com/romanzoller/mfp-json/blob/7a62157b247c36f8aef03ef4d3da74e4bb02c6c4/requestData.json#L5) and then doing [some hacks in the report template](https://github.com/romanzoller/mfp-json/blob/7a62157b247c36f8aef03ef4d3da74e4bb02c6c4/json_demo_main.jrxml#L11-L16) to convert the stringified data to a `JsonDataSource`, it is already possible to do this with mapfish print.

However, it would be better to have a JSON data type in mapfish print to handle this case, an illustration of the potential simplifications of this use case is given [here](https://github.com/romanzoller/mfp-json/compare/json-type).

What would need to be implemented, as far as I can tell:

- Accept `!json` as a type in `config.yaml`
- Read request data as JSON for attributes of that type
- Provide the data to the report template as an instance of `net.sf.jasperreports.engine.data.JsonDataSource`

**Comment by romanzoller** [comment]
Comment from @sbrunner:

> We will add an attribute of type json which will provide a value of type Object, which can be any of
> - PArray
> - PObject
> - String
> - Double
> - Long

=> Question: How will this Object be exposed to the jasper reports template? Is it going to be `net.sf.jasperreports.engine.data.JsonDataSource`?

**Comment by sbrunner** [comment]
Yes it can be good but it's more complex to create :-)

**Comment by vvmruder** [comment]
This feature is what we would need for pyramid_oereb too.

But iam interested in a java native json like representation (like dict in python) which enables me to access values in arbitrary deep json.

**Comment by pvalsecc** [comment]
Working on it and investigating what is the proper type to use.
