### ISSUE TITLE
throwErrorOnExtraParameters is not documented

### ISSUE THREAD

**Issue by romanzoller** [mapfish/mapfish-print#666]
The following appears in several examples:

```
throwErrorOnExtraParameters: true
```

It is missing in the generated documentation, but is documented in [the code](https://github.com/mapfish/mapfish-print/blob/1ea6051147541bfb5c6e25c111581973fd477159/core/src/main/java/org/mapfish/print/config/Configuration.java#L451-L454) as:

>     /**
>      * If true then if the request JSON has extra parameters exceptions will be thrown.  Otherwise the
>      * information will be logged.
>      */

The documentation is not quite accurate, see discussion below.

**Comment by pvalsecc** [comment]
It is documented there:
https://github.com/mapfish/mapfish-print/blob/master/core/src/main/java/org/mapfish/print/config/Configuration.java#L452

For some reason the documentation generation is not picking it up.

**Comment by romanzoller** [comment]
Ok, but in this case it's not working properly, I will edit the issue...

**Comment by pvalsecc** [comment]
I'm working on a fix fir the documentation

**Comment by pvalsecc** [comment]
In fact, the documentation is a bit wrong... that stuff is only used to detect extra parameters in the layer configurations. Should we fix the doc or should we fix the code to detect extra parameters in the attributes as well?

**Comment by romanzoller** [comment]
Both would be fine with me, but changing the behavior would be a breaking change which might affect quite a lot of applications, so I would tend to prefer fixing the doc.

**Comment by pvalsecc** [comment]
OK, fixing the doc

**Comment by sbrunner** [comment]
For me we should fix it and marked as a potential breaking change...

**Comment by pvalsecc** [comment]
This is not a 5 minute fix anymore. I'll fix the doc and leave this ticket open, then.

**Comment by sbrunner** [comment]
OK, +1 :-)

**Comment by romanzoller** [comment]
Ok, let's not mix up the 2 things, if you want to create a new issue for the changed behavior, here is the example:

It doesn't seem to work like that, e.g. I would have expected an error to be thrown with the flag set when passing an attribute `"foo": "bar"` in the `attributes` Object of the pdf generation request, since I didn't specify a `foo` attribute in my `config.yaml`, but no error was thrown.

**Comment by pvalsecc** [comment]
Online doc updated. I'll let @romanzoller create the new ticket.

**Comment by romanzoller** [comment]
As I said, I'm happy with the fixed doc, if anyone else is not, feel free to create an issue.
