### ISSUE TITLE
Port to java 11 (LTS)

### ISSUE THREAD

**Issue by pvalsecc** [mapfish/mapfish-print#673]
Before starting that, we must wait for geotools to do their part: https://github.com/geotools/geotools/wiki/Java-9-Compatibility

Maybe Jasper Reports has trouble too.

**Comment by pvalsecc** [comment]
GeoTools 11 should work, as of 21.0.

Jasper Reports not.

**Comment by jgrocha** [comment]
Geoserver 2.15.0 (and Geotools) are running fine with Tomcat9 and java-11-openjdk-amd64

I've tried to run MapFish print-servlet-3.19.0.war on the same Tomcat9 instance, running java-11-openjdk-amd64 and MapFish fails with:
```
22-Apr-2019 09:30:07.035 INFO [report subreports #1] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.sun.media.imageio.stream.RawImageInputStream]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.sun.media.imageio.stream.RawImageInputStream]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
```

Using java-8-oracle with JAI works great.

**Comment by pvalsecc** [comment]
Yep, still waiting for support in Jasper Reports...

**Comment by TDesjardins** [comment]
> Yep, still waiting for support in Jasper Reports...

Seems that Jasper Reports works with 11 now:
https://github.com/TIBCOSoftware/jasperreports/issues/43

**Comment by sebr72** [comment]
Now done
