### ISSUE TITLE
Add an accounting module

### ISSUE THREAD

**Issue by pvalsecc** [mapfish/mapfish-print#676]
For being able to offer print as a service, we would need an accounting module. Something that stores (PG DB) what template was printed on what application from what referer.

**Comment by pvalsecc** [comment]
Number of pixels?

**Comment by sbrunner** [comment]
Finally we needs?:
- The application name
- The template name
- The referer
- The maps size / or the number of pixels
- The DPI / or the number of pixels
- The number of layers
