### ISSUE TITLE
print-apps missing in 3.15 war package

### ISSUE THREAD

**Issue by jgrocha** [mapfish/mapfish-print#695]
Hi,

I've just installed 3.15 version (from war). I noticed that print-apps folder is no longer available in the war package. Without print-apps the service does not start.

I had to manually create print-apps and copy all the layouts from another Mapfish installation.

Thanks!

**Comment by sbrunner** [comment]
Effectively you had to copy your application in the print-apps folder, previously we put all the examples in print apps but it can be a security issue...

**Comment by jgrocha** [comment]
Thanks @sbrunner for the feedback.
