### ISSUE TITLE
Question about method plr_tolerance_check()

### ISSUE THREAD

**Issue by svareg** [mapfish/mapfish-print#776]
Hello,

Sometimes, when creating an extract, the intersecting features are not listed in the "concerned themes".

I identified that the result of _st_intersects()_ returns the right features from DB. 
But then they are removed from the concerned theme in the function _processor.plr_tolerance_check()_.
Actually, they are removed because they don't intersect exactly : there is a distance from **0.1 mm** between the features, and the line if not exactly on the polygon edge.

Is this _"normal"_ ?
I don't really understand why this check was added here. Can someone explain this ?
Why don't we just use the result of st_intersect sent by the DB ?
Perhaps should it be configurable ?

Thanks!

**Comment by pvalsecc** [comment]
Serious lack of context, here... What version? What processor? Where is that function?

**Comment by svareg** [comment]
Hey, I posted this issue to the wrong place... This was meant to be published in "pyramid_oereb" repository...

My failure, sorry !
