### ISSUE TITLE
vector style for polygon with hatch

### ISSUE THREAD

**Issue by g-hawk** [mapfish/mapfish-print#899]
Hi to all,

there is a manner to define, for a vector polygon,  a style with hatching pattern?
For line there is a strokeDashstyle that permit to print different line type. I want fill polygons on vector layer with some type of hatching pattern rather than coloring it in a uniform way.
Thanks.

Giuseppe

**Comment by pvalsecc** [comment]
https://docs.geoserver.org/stable/en/user/styling/sld/cookbook/polygons.html#hatching-fill

**Comment by g-hawk** [comment]
Hi,

thanks for the response.
I apologize, but I did not understand correctly. I have a geojson layer. 
It is not possible for this layer to define a style (with hatch) following the mapfish json style version 2?
In the posted link there is a refer to a sld syntax for hatched style.
Thanks.

Giuseppe

**Comment by pvalsecc** [comment]
AFAIK, you can use directly the SLD styling in mapfish print.

**Comment by kflaw** [comment]
How do you apply the SLD styling to a geojson in mapfish?

**Comment by sbrunner** [comment]
Like that:
https://github.com/mapfish/mapfish-print/blob/68161f4a34326736c64cdaa27bf9500fca762320/core/src/test/resources/org/mapfish/print/processor/setstyle/basic/request.json
or:
https://github.com/mapfish/mapfish-print/blob/68161f4a34326736c64cdaa27bf9500fca762320/core/src/test/resources/org/mapfish/print/processor/map/center_osm_fixedscale_dpi/requestData.json#L11

**Comment by kflaw** [comment]
Thanks for this! I tried inserting the SLD string but formatting was not right. Got it working now!

**Comment by sureshenercomp** [comment]
how to apply hatched polygon on vector feature of ol instead  of whole layer for mapfish-print
