### ISSUE TITLE
Red squares instead of north arrow and scalebar on mobile device

### ISSUE THREAD

**Issue by rbovard** [mapfish/mapfish-print#988]
**Context** : https://geomapfish-demo.camptocamp.com/2.3-docker/
* MapFish print version: ?
* Java version: ?
* OS: ?

The generated PDF had red squares instead of north arrow and scalebar on mobile device (Android 9) with Adobe Acrobat Reader.

![image](https://user-images.githubusercontent.com/4549666/60715314-051a7a00-9f1d-11e9-9f79-bd70e7b87e98.png)

Try to open attached PDF
[mapfish-print-report.pdf](https://github.com/mapfish/mapfish-print/files/3362150/mapfish-print-report.pdf)

**Comment by pvalsecc** [comment]
Red square == missing images (cannot download)

But I cannot reproduce. I've tried:
* got to https://geomapfish-demo.camptocamp.com/2.3-docker/theme/Demo?lang=en&tree_groups=OSM%20functions%20mixed%2CLayers%2CGroup%2COSM%20functions%2CExternal%2CFilters%20mixed%2CFilters&tree_group_opacity_Group=0.65&tree_enable_osm_scale=true&tree_group_layers_Layers=cinema%2Cpost_office%2Centertainment%2Csustenance&tree_group_layers_Group=&tree_group_layers_OSM%20functions=osm_scale&tree_group_layers_External=&tree_enable_osm_open=false&tree_enable_ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung=false&tree_enable_OSM%20map=false&tree_enable_osm_time_r_dp_2=false&tree_group_layers_Filters=&baselayer_ref=OSM%20map
* print
* un check legend
* layout: A4 portrait

I do get the scale and north arrow OK. But the map gets a pinkish background (another problem with the sustenance, entertainment, post_office and cinema layers).

Can you still reproduce? How exactly?

Can you still reproduce?

**Comment by rbovard** [comment]
Thanks for your investigation @pvalsecc 

Did you tried to open the generated PDF on a Android device? I tried with your steps and I've the red squares (in desktop environment it's ok).

![image](https://user-images.githubusercontent.com/4549666/61640707-18a83d80-ac9e-11e9-889f-7afc2af75bd9.png)

My mobile config: Android 9, [Adobe Acrobat Reader](https://play.google.com/store/apps/details?id=com.adobe.reader) (v19.4)

**Comment by pvalsecc** [comment]
I guess we are having the same problem as this guy: https://community.jaspersoft.com/questions/1080756/chart-appears-red-colour-android-mobile-acrobat-reader
We had the same problem reported from another customer a few month ago and it was ruled out as a bug in acrobat reader on Android. Please use another reader.

**Comment by rbovard** [comment]
Oh I see, sad.

Do you know if there is a place to report this issue to Adobe?

**Comment by pvalsecc** [comment]
From the playstore info, I'd say: adobereader-android@adobe.com
